### ISSUE TITLE
Query data from Object Store

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#1082]
__Use case:__
When data is persisted in object store that is done in #808, our Query Server needs to read that data from object store if they no longer exist in Read Buffer. We will see which of the following we will implement first

 1. Will we query parquet files directly or first load them into the read buffer
 2. Do we need to persist a serialized catalog for v1 or can we just list objectstore files

TBD: How to do it 

__Proposal:__
Short summary of the feature.

__Current behaviour:__
Describe what currently happens.

__Desired behaviour:__
Describe what you want.

__Alternatives considered:__
Describe other solutions or features you considered.

**Comment by alamb** [comment]
The high level idea is probably to implement `DBChunk::ParquetFile`: https://github.com/influxdata/influxdb_iox/blob/7154dfd5f61232076a3336479ee98870bdc602c2/server/src/db/chunk.rs#L71

Since the query engine is implemented in terms of (effectively) `DBChunk` as long as parquet files can provide all the data as the other types of chunks, query should "just work"
