### ISSUE TITLE
Error creating scan for table http_api_requests_total chunk Read Buffer Error in chunk chunk id does not exist

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#1130]
```
alamb@ip-10-0-0-124 influxdb_iox % ./target/debug/influxdb_iox --host http://localhost:1234 database query 844910ece80be8bc_7be09b71c487d5d3 "select count(*) from http_api_requests_total;"
./target/debug/influxdb_iox --host http://localhost:1234 database query 844910ece80be8bc_7be09b71c487d5d3 "select count(*) from http_api_requests_total;"
Error querying: status: Internal, message: "Internal error reading points from database 844910ece80be8bc_7be09b71c487d5d3:  Arrow error: External error: Execution error: Error creating scan for table http_api_requests_total chunk 146: Read Buffer Error in chunk 146: chunk id does not exist: 146", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Tue, 06 Apr 2021 16:31:32 GMT"} }
alamb@ip-10-0-0-124 influxdb_iox % 
```

__Steps to reproduce:__
Try to query a database that has data being written to it actively and that the chunk lifecycle rules cause data to get dropped out of the read buffer

The query will work, but occasionally it will fail with the error above

__Expected behaviour:__
The query should complete successfully

__Actual behaviour:__

Error : "Error creating scan for table http_api_requests_total chunk 146: Read Buffer Error in chunk 146: chunk id does not exist: 146","

__Environment info:__
internal tools cluster

**Comment by tustvold** [comment]
This appears to be a bug in DbChunk::snapshot as it currently defers the read buffer chunk lookup until query execution. This means that if a chunk is dropped from the read buffer between query plan and execution, it will result in this error.

This will be fixed by making catalog own read buffer chunks (#1042), and DbChunk::snapshot copy Arcs to the underlying chunk data. This will defer freeing the chunk data until all outstanding queries against it have completed.
