### ISSUE TITLE
Large volumes of data being transferred using `influxdb_iox database query` command

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#1133]
Broken off from https://github.com/influxdata/influxdb_iox/issues/1132

__Steps to reproduce:__
@mkmik  noticed when running the following command:

```
$ while true; do ./target/debug/influxdb_iox --host http://localhost:1234  database query 844910ece80be8bc_7be09b71c487d5d3 "select * from http_api_requests_total limit 10;"; done
```

there was 3Mbps of data while being downloaded while doing. Wireshark shows a conversation of 22Mb:

![image](https://user-images.githubusercontent.com/490673/113778020-dfc22d80-96f9-11eb-8e72-0ce7acdb03e2.png)

When the results displayed to the user are on the order of 1K

__Expected behaviour:__
Traffic size in proportion to the size of the results returned

__Actual behaviour:__
22MB is several orders of magnitude greater than the results returned

**Comment by mkmik** [comment]
the wireshark gRPC dissector works well once you add the .proto files. However Apache Flight is all 'bytes' containing flatbuffer payloads, which can be decoded with `flatc -t`.

Turns out `select * from http_api_requests_total limit 10;` returns a single big recordbatch response of 22Mb.

While `select nodename from http_api_requests_total limit 1;` returns a single big recordbatch resposne of 3Mb.

Passing the `data_header` payload to `flatc -t` we can see:

```
{
  version: "V5",
  header_type: "RecordBatch",
  header: {
    length: 1,
    nodes: [
      {
        length: 1,
        null_count: 0
      }
    ],
    buffers: [
      {
        offset: 0,
        length: 8752
      },
      {
        offset: 8752,
        length: 280008
      },
      {
        offset: 288760,
        length: 2848784
      }
    ]
  },
  bodyLength: 3137544
}
```

by changing the limit, the record batch `length` field changes, but the size of the overall body stays about 3Mb.

Once the `limit` crosses about 70000, we start receiving new result batches, each about 3mb in size, no matter what's the length of the actual record batch. Some printf debugging:

```
Received response:
data_header.len = 144
data_body.len = 3131920
batch = RecordBatch { length: 70000, nodes: Some([FieldNode { length: 70000, null_count: 0 }]), buffers: Some([Buffer { offset: 0, length: 8752 }, Buffer { offset: 8752, length: 280008 }, Buffer { offset: 288760, length: 2843160 }]), compression: None }

Received response:

data_header.len = 144
data_body.len = 3131920
batch RecordBatch = { length: 100, nodes: Some([FieldNode { length: 100, null_count: 0 }]), buffers: Some([Buffer { offset: 0, length: 8752 }, Buffer { offset: 8752, length: 280008 }, Buffer { offset: 288760, length: 2843160 }]), compression: None }
```

**Comment by mkmik** [comment]
This problem doesn't manifest when using the old http API:

```console
$ time curl -s "http://localhost:8080/iox/api/v1/databases/844910ece80be8bc_7be09b71c487d5d3/query?q=SELECT%20*%20FROM%20http_api_requests_total%20limit%2010" >/tmp/fast
curl -s  > /tmp/fast  0.00s user 0.00s system 1% cpu 0.578 total
```

**Comment by mkmik** [comment]
the problem is simply that a RecordBatch of size 10, with a column whose Array is of size 10, points to ArrayData of size 10, which contains one or more Buffers, pointing the the underlying backing store of 3Mb of data, containing all elements.

The `write_array_data` function (https://github.com/apache/arrow/blob/master/rust/arrow/src/ipc/writer.rs#L705) produces a wire encoding that copies the content of the original buffers, instead of re-coding a new array.

Presumably the primary use case for flight favours sending large original arrays around and not just "slices".

**Comment by mkmik** [comment]
Datafusion's LIMIT plan ultimately calls `arrow::compute::limit` to produce a limited array, which tries to do the cheapest possible thing, by just calling `.slice()`

https://docs.rs/arrow/3.0.0/src/arrow/compute/kernels/limit.rs.html#28
```rust
pub fn limit(array: &ArrayRef, num_elements: usize) -> ArrayRef {
    let lim = num_elements.min(array.len());
    array.slice(0, lim)
}
```

**Comment by mkmik** [comment]
When the execution is in memory, datafusion's behavior makes perfect sense: there is no need to create a new array and copy data into it.

When serializing to flatbuffers though, it's hard for arrow-flight to know whether it pays to create and encode a smaller array by materializing the limit. It's hard for arrow-flight to even know that the array batch being encoded is a product of a limit-like operation; it could compare the length of the ArrayData with the sizes of the underlying buffer and apply a heuristic though.

**Comment by mkmik** [comment]
#1136 implements a hackish workaround.

On the long run, can we consider rewriting the limit plan into something that materializes the limit?

**Comment by mkmik** [comment]
w.r.t #1136, we may want to consider if it's possible to do this "shrinking"  on the fly in `flight_data_from_arrow_batch`, since that function ultimately copies an array into a `Vec<u8>` and pass it to flatbuffer.

**Comment by alamb** [comment]
@mkmik  I think the right fix is as you say -- to send only those bytes actually used from the underlying record batch's Buffer across the wire

**Comment by mkmik** [comment]
Reported in https://issues.apache.org/jira/browse/ARROW-12265

**Comment by alamb** [comment]
I think this ticket is done so closing it. Further improvements are tracked with https://issues.apache.org/jira/browse/ARROW-12265

**Comment by alamb** [comment]
Update -- new tracking upstream ticket is https://github.com/apache/arrow-rs/issues/208
