### ISSUE TITLE
Sort Order In Schema

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#1357]
Many operations can exploit sort order to be performed more efficiently, for example, merging chunks, filtering and indexing. We should codify this in the IOx schema, i.e. as arrow metadata, so that it can be exploited by logic within IOx.

@alamb I understand has some ideas on how this might be generalized to the point where Datafusion could exploit it

**Comment by alamb** [comment]
What I imagine is a semi-standardized way to attach sort order to the Arrow RecordBatch by keeping a list of 

(column_name, sort asc/desc, nulls_first/last)

Ideally this encoding would be part of DataFusion too so that we could take advantage of the information at both plan time (aka optimize away sorts if the data was already sorted that way)
