### ISSUE TITLE
Management API to persist a chunk

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#1935]
__Use case:__
1. As an operator, when I have chunks that are persisted quickly enough by the the lifecycle policy manager (e.g. because I know I am going to shut the server down), I want a way to force chunks to be persisted in advance. 
2. As someone who wants to implement a merge policy that is different than the one built into IOx, I want to be able to do the same operations as the built in policy
2. As a developer, I want to be able to setup an end to end integration into exactly the state I need to test

Related to the "unload from memory" api here: https://github.com/influxdata/influxdb_iox/issues/1919

__Proposal:__
Add a "persist" Management API and CLI which takes as input a `partition_key`, a list of chunks, and a "split time" and combines those chunks into two parts: all rows prior to the split time in a persited parquet chunk, and all rows after the  split time as RUB chunk

**Comment by alamb** [comment]
I am not sure about this one FYI @pauldix

**Comment by pauldix** [comment]
@alamb I agree, we should support this. I think it should be possible to turn the lifecycle manager off completely and drive it totally through API requests.

**Comment by crepererum** [comment]
As of #1972 we don't have an internal API to persist single chunks any longer because it doesn't work well with the new lifecycle and the checkpointing involved, since that would allow the user to persist data out of order (aka not following the persistence windows construct). Instead we now have an internal API to trigger persistence for an entire partition.

So I would like to change the focus of this issue from "Management API to persist a chunk" to "Management API to persist a partition".

**Comment by alamb** [comment]
Makes sense @crepererum  -- maybe it makes even more sense to file a new ticket for `Management API to persist a partition` and close this one
