### ISSUE TITLE
Db reading from Kafka doesn't see any partitions if there have never been any writes to Kafka; never updates

### ISSUE THREAD

**Issue by carols10cents** [influxdata/influxdb_iox#2189]
## What happened

- I started a Kafka instance
- I started an IOx server and created a database configured to write to Kafka. **I did not write any points to this database on this server**.
- I started another IOx server and created a database configured to read from Kafka. I saw this in the logs:

```
INFO write_buffer::kafka: found Kafka partitions database_name=mydb_test partitions=[]
```

- **Then** I wrote to the server/db that writes to Kafka. In the server with the writer database, I see this in the logs:

```
write_buffer::kafka: wrote to kafka db_name=mydb_test offset=4 partition=0 size=7088
```

I don't see anything in the logs of the server/db that reads from Kafka.

## What I expected

If instead of the sequence of steps above, I perform them in this order:

- Create database that writes to Kafka
- Write some points
- Create database that reads from Kafka

Then I see in the reader's logs:

```
INFO write_buffer::kafka: found Kafka partitions database_name=mydb_blah partitions=[0]
```

(note partitions is `[0]` instead of `[]`)

and continuing to write to the writer db does get picked up by the reader.

It looks like if Kafka doesn't have any partitions in it for the database when the reader gets created, then it will never pick up any partitions...

**Comment by carols10cents** [comment]
Aha, looks like this might be a known issue? https://github.com/influxdata/influxdb_iox/blob/e2df0eeb008f28a76af640714ee5ca5de7ecfca1/tests/end_to_end_cases/write_buffer.rs#L161

**Comment by carols10cents** [comment]
Looks like that comment was added in https://github.com/influxdata/influxdb_iox/pull/2044, and one of the reasons for this change was to support databases that have multiple Kafka partitions-- do we currently have any of those, though?

Possible solutions:

- Change consumers so that they periodically check for new partitions; this seems like the "real" fix but nontrivial
- Change producer so that it creates a partition when we create the producer; this will still mean we have to create the database writing to Kafka before we create the database reading to Kafka, but at least it would remove the need to write some data to the writer before creating the reader
- Change consumers so that if there are no Kafka partitions, creating the database fails, so at least we get an error rather than a database that exist but never gets any data from Kafka
- Something else?

**Comment by crepererum** [comment]
# Topics VS Partitions
I think there might be something missing here: The set of partitions within a topic MUST NOT change after we start consuming or producing, otherwise the whole "where does which data part of the data" will break and sequence orders become senseless. So what you rather want is "wait for until the topic is created" (if that's possible, see cases in "topic/partition creation").

I actually even wanted to add a check to the Kafka consumer that bails out when this is happening.

# Topic/Partition Creation
I'm missing something from your "what I did" description above: when do you create the topic using the admin API? I'm wondering if the issue is either:

1. that the consumer only sees non-empty topics
2. that we're creating the topic after we start consuming and therefore the consumer thinks the set of partitions is empty.

## Case 1
When (1) holds:

### Solutions
> Change consumers so that they periodically check for new partitions; this seems like the "real" fix but nontrivial

I think that might be possible if we instead of returning a fixed list of "streams" from the consumer, we produce a "stream of streams". However I'm somewhat worried about the expansion of topics, see first subsection.

> Change consumers so that if there are no Kafka partitions, creating the database fails, so at least we get an error rather than a database that exist but never gets any data from Kafka

Is that possible in this case? Is a topic w/ all partitions created on first write? Or is a partition created on firs

## Case 2
When (2) holds:

### Use Case
I also wonder what the use case is for "start a DB but later create the topic" because this sounds like we instruct a server to be based on a data stream that we may wanna modify in the future.

### Solutions
Regarding your potential solutions:


> Change consumers so that they periodically check for new partitions; this seems like the "real" fix but nontrivial

Since the set of partitions must not change, I think this is not a solution. What however could be one is to "wait for any partition to appear and freeze the set at this point" aka "wait until the topic is created".

> Change producer so that it creates a partition when we create the producer...

Please let's not do that. Topic creations should be an explicit action. Implicit topic creations require you to know the number of partitions (that could be done). Implicit partition additions is a no go (see above).

> Change consumers so that if there are no Kafka partitions, creating the database fails, so at least we get an error rather than a database that exist but never gets any data from Kafka

Depending on the answer to the use case question above, that would be my preferred approach.

**Comment by carols10cents** [comment]
> when do you create the topic using the admin API?

So the way I ran into this is [making this script](https://github.com/influxdata/iox_data_generator/blob/master/src/bin/create_database.rs) that sets up some databases for testing with the data generator. Right now it needs [these writes](https://github.com/influxdata/iox_data_generator/blob/a1a7f708591460cefa8522f7dd949fc1d3cd420b/src/bin/create_database.rs#L131-L142) before [creating the reader database](https://github.com/influxdata/iox_data_generator/blob/a1a7f708591460cefa8522f7dd949fc1d3cd420b/src/bin/create_database.rs#L144-L155) or else the reader database never sees any data. I don't think those writes should be necessary, and I don't think this code should need to communicate with Kafka directly to create a topic. The only thing this code needs to know about Kafka is the URL that the databases can use in their database rules.

Currently, I see nowhere in `write_buffer/src/kafka.rs` that is creating a topic explicitly. I see in b5428e53a594efe1a5a7ed7fa9b7e412650f6546 you say:

> **Partition on Write:** The caller of the writer operation must now
  specify the partition/sequencer ID. The implicit partitioning of the
  Kafka writer would have lead to broken data since we must never spill
  entries w/ the same primary key over multiple partitions. At the
  moment we will only use partition 0 but we can easily implement
  better logic in the future.

But the only place in that commit I see creating a topic [is in test code](https://github.com/influxdata/influxdb_iox/commit/b5428e53a594efe1a5a7ed7fa9b7e412650f6546#diff-73f0baeb2ae102aaf6ffa910c45d31a1bdcd78c5d498e2bf55660d16a2bd41aaR244-R253). My fault for missing that in the review :) With what you've said above, it sounds like the non-test write buffer producer should be creating the *topic* in `KafkaBufferProducer::new`, before the first write. Right now it seems like the topic is being created implicitly on first write.

Creating the topic when we create the `KafkaBufferProducer` still means that we have to create a database writing to Kafka before we create a database reading from Kafka, so I think erroring when creating a database reading from Kafka that doesn't see any partitions is needed too.

**Comment by crepererum** [comment]
I think the producer shouldn't create the topic at all. It should be done externally by conductor / the admin before reads and writes happen. That's similar to how object stores are handled (we also don't auto-create buckets). I think our current config does that by accident rather than by design, but that should probably be disabled (see `allow.auto.create.topics` in https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md ). However I'm probably not the person who should have the last word on this, so paging let's ask the conductor team for their opinion:

@mkmik @domodwyer: Should a Kafka producer auto-create topics or should that always be done by another actor (conductor, some admin, some K8s deploy foo)? The background is that it would be easier if the set of partitions within a topic is properly set+fixed when IOx starts to interact with it.

**Comment by mkmik** [comment]
The current assumption is that conductor creates the topic.

**Comment by carols10cents** [comment]
Ok. So then it sounds like the best solution here is for creation of a database reading from Kafka to error if it can't find any partitions, with a suggestion to create a Kafka topic then try again.
