### ISSUE TITLE
IOx unlikely to run correctly on  aarch64-apple-darwin

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb_iox#2270]
Currently there are some issues around `Instant` and duration calculations that have been observed locally on `aarch64` running `macOS`. These result in failing tests.

Perhaps related to rust-lang/rust#87906 but not clear yet.

It is likely IOx isn't going to work correctly on these architectures until these issue are resolved.

**Comment by crepererum** [comment]
IMHO "IOx runs on aarch64" should only be advertised when we have an aarch64 CI that ensures that. [CircleCI seems to offer some support for that](https://circleci.com/docs/2.0/arm-resources/).

**Comment by mkmik** [comment]
I couldn't reproduce this issue on `aarch64-unknown-linux-musl` (executed on qemu) but only on `aarch64-apple-darwin` (running on a M1 mac). I don't think CircleCI offers yet M1 macs?

**Comment by tatsuya6502** [comment]
Hello.

I believe this is macOS AArch64 platform specific issue (and Linux AArch64 will be OK).

I lightly reviewed the failing tests in IOx. I think they are failing because there are some rounding errors between nanoseconds and OS kernel's native monotonic time. While `std::time::Duration` uses seconds and nanoseconds to represent a duration, `std::time::Instant` is opaque and can use a different time unit like the one that OS kernel uses.

----

**Duration**

https://doc.rust-lang.org/stable/std/time/struct.Duration.html
> Each `Duration` is composed of a whole number of seconds and a fractional part represented in nanoseconds.

**Instant**

https://doc.rust-lang.org/stable/std/time/struct.Instant.html
> Opaque and useful only with `Duration`.

https://doc.rust-lang.org/stable/std/time/struct.Instant.html#os-specific-behaviors
> An `Instant` is a wrapper around system-specific types and it may behave differently depending on the underlying operating system.

----

When you add a `Duration` to `Instant`, the duration (nanoseconds) has to be converted to the time unit used by instant. This conversion can produce a small rounding error. I think all of the failing tests do such calculation (instant + duration [+ duration ..]) and expect `Instant` to provide nanosecond accuracy. They are failing on macOS AArch64 because `Instant` on that platform does not provide such accuracy.

Here are more details.

I checked the source code of `std::time::Instant` and found it uses "mach tick unit" on macOS and iOS. `std::time::Instant` on these platforms internally calls Mach kernel's `mach_timebase_info` function, which returns [fraction to multiply a value in mach tick units with to convert it to nanoseconds](https://developer.apple.com/documentation/driverkit/3433733-mach_timebase_info).

I copied some codes from `std::time::Instant` and ran it on my Intel and M1 Macs. I found the followings:

- On an Intel Mac (x86_64) running macOS Catalina, 1 mach tick is 1 nanosecond. 
   - NOTE: My Intel Mac is a bit old and cannot run macOS Big Sur. There might be a chance a newer Intel Mac running Big Sur to return a different result)
- On a M1 Mac (AArch64) running macOS Big Sur, 1 mach tick is 125/3 nanoseconds (~= 41.6666666..)

<details>
 <summary><strong>The code:</strong> (Click to expand)</summary>

```rust
// Cargo.toml
//
// [dependencies]
// libc = "0.2.99"

use std::time::{Duration, Instant};

fn main() {
    use std::env::consts::{ARCH, OS};

    println!("Running on {} {}.", OS, ARCH);
    println!("");

    let mach_tick_info = instant::info();
    println!("{:?}", mach_tick_info);

    println!("----------------------------------------");
    println!(
        "  1 mach tick   ~= {:3.8} nanosecond(s)",
        mach_tick_info.numer as f64 / mach_tick_info.denom as f64,
    );
    println!("----------------------------------------");

    println!(
        "  1 nanosecond  ~= {:3} mach tick",
        instant::checked_dur2intervals(&Duration::from_nanos(1)).unwrap()
    );

    println!(
        " 42 nanoseconds ~= {:3} mach tick(s)",
        instant::checked_dur2intervals(&Duration::from_nanos(42)).unwrap()
    );

    println!(
        "100 nanoseconds ~= {:3} mach ticks",
        instant::checked_dur2intervals(&Duration::from_nanos(100)).unwrap()
    );

    println!("----------------------------------------");
    let now = Instant::now();
    let dur1 = Duration::from_nanos(999);
    let dur2 = (now + dur1).duration_since(now);
    println!(
        "Duration {} nanoseconds => Instant => Duration {:?} nanoseconds",
        dur1.as_nanos(),
        dur2.as_nanos()
    );
}


#[cfg(any(target_os = "macos", target_os = "ios"))]
mod instant {
    use std::time::Duration;

    // The most of the codes in this module were copied from:
    // https://github.com/rust-lang/rust/blob/master/library/std/src/sys/unix/time.rs

    const NSEC_PER_SEC: u64 = 1_000_000_000;

    #[repr(C)]
    #[derive(Copy, Clone, Debug)]
    pub(crate) struct mach_timebase_info {
        pub(crate) numer: u32,
        pub(crate) denom: u32,
    }

    #[allow(non_camel_case_types)]
    type mach_timebase_info_t = *mut mach_timebase_info;

    #[allow(non_camel_case_types)]
    type kern_return_t = libc::c_int;

    extern "C" {
        fn mach_timebase_info(info: mach_timebase_info_t) -> kern_return_t;
    }

    pub(crate) fn checked_dur2intervals(dur: &Duration) -> Option<u64> {
        let nanos = dur
            .as_secs()
            .checked_mul(NSEC_PER_SEC)?
            .checked_add(dur.subsec_nanos() as u64)?;
        let info = info();
        Some(mul_div_u64(nanos, info.denom as u64, info.numer as u64))
    }

    pub(crate) fn info() -> mach_timebase_info {
        let mut info = mach_timebase_info { numer: 0, denom: 0 };
        unsafe {
            mach_timebase_info(&mut info);
        }
        info
    }

    // The following function was copied from:
    // https://github.com/rust-lang/rust/blob/master/library/std/src/sys_common/mod.rs#L79-L90

    // Computes (value*numer)/denom without overflow, as long as both
    // (numer*denom) and the overall result fit into i64 (which is the case
    // for our time conversions).
    pub fn mul_div_u64(value: u64, numer: u64, denom: u64) -> u64 {
        let q = value / denom;
        let r = value % denom;
        // Decompose value as (value/denom*denom + value%denom),
        // substitute into (value*numer)/denom and simplify.
        // r < denom, so (denom*numer) is the upper bound of (r*numer)
        q * numer + r * numer / denom
    }
}

#[cfg(not(any(target_os = "macos", target_os = "ios")))]
mod instant {
    use std::time::Duration;

    #[allow(non_camel_case_types)]
    type mach_timebase_info_t = ();

    pub(crate) fn checked_dur2intervals(dur: &Duration) -> Option<u64> {
        unimplemented!()
    }

    pub(crate) fn info() -> mach_timebase_info {
        unimplemented!()
    }
}
```
</details>


**Results**

Intel Mac (x86_64):

```console
Running on macos x86_64.

mach_timebase_info { numer: 1, denom: 1 }
----------------------------------------
  1 mach tick   ~= 1.00000000 nanosecond(s)
----------------------------------------
  1 nanosecond  ~=   1 mach tick
 42 nanoseconds ~=  42 mach tick(s)
100 nanoseconds ~= 100 mach tick
----------------------------------------
Duration 999 nanoseconds => Instant => Duration 999 nanoseconds
```

M1 Mac (AArch64):

```console
Running on macos aarch64.

mach_timebase_info { numer: 125, denom: 3 }
----------------------------------------
  1 mach tick   ~= 41.66666667 nanosecond(s)
----------------------------------------
  1 nanosecond  ~=   0 mach tick
 42 nanoseconds ~=   1 mach tick(s)
100 nanoseconds ~=   2 mach ticks
----------------------------------------
Duration 999 nanoseconds => Instant => Duration 958 nanoseconds
```

To make the failing tests to run reliably on macOS AArch64, we need to make them to use an error tolerance. Instead of checking equality, they should measure the difference between the expected and actual values and if the difference is smaller than the error tolerance, they should pass.

Maybe I can work on the fix. This looks like a good first issue to work on because it does not require any knowledge specific to the design of IOx.

**Comment by e-dard** [comment]
@tatsuya6502 Hi there! 

Thank you for the comment and testing code. I think asserting a test result is within some epsilon is a good way to address the inaccuracies on the `aarch64-apple-darwin` platform.

I think the team will need to have a wider conversation internally about what to do in general about this problem, as I believe in some cases we rely on the accuracy of clocks for ordering internally in IOx. So if we want to support IOx on `aarch64-apple-darwin` (which I personally would like) then we might need to do some extra work.

**Comment by e-dard** [comment]
(After a brief chat internally it sounds like we will be ok on `aarch64-apple-darwin` - we only need a monotonic property rather than nanosecond precision).

**Comment by carols10cents** [comment]
Thank you for that very in-depth analysis, @tatsuya6502 !

**Comment by tatsuya6502** [comment]
> (After a brief chat internally it sounds like we will be ok on aarch64-apple-darwin - we only need a monotonic property rather than nanosecond precision).

Sounds good. So only test cases need to be updated for aarch64-apple-darwin. I will start to work on it (maybe this weekend) and share my progress.

**Comment by jacobmarble** [comment]
@e-dard would this be covered by your recent M1 test bot?

**Comment by tatsuya6502** [comment]
Sorry for not creating a pull request. I have done some work in my fork.
https://github.com/influxdata/influxdb_iox/compare/main...tatsuya6502:tatsuya/fix-mac-aarch64-tests

@e-dard Please let me know if you still need my work. I will be able to work on this in next few days.

**Comment by tustvold** [comment]
The offending tests, and accompanying logic, were removed in the time provider rework #2722
