### ISSUE TITLE
create DB should work when DB is known but no active generations are found

### ISSUE THREAD

**Issue by crepererum** [influxdata/influxdb_iox#2484]
__Steps to reproduce:__
1. create a object store folder structure that is contain a folder per DB and these folders only contain "garbage" files (aka no generation ID)
2. start  IOx
3. DBs are in error state because no active generation can be found
4. try to create DB => fails

This happens after deploying #2355.

__Expected behaviour:__
"create DB" should work

__Actual behaviour:__
Nothing happens.

__Logs:__
```console
$ ./scripts/grpcurl -plaintext localhost:1234 influxdata.iox.management.v1.ManagementService.GetServerStatus
{
  "serverStatus": {
    "initialized": true,
    "databaseStatuses": [
      {
        "dbName": "XXX",
        "error": {
          "message": "no active generation directory found, not loading"
        },
        "state": "DATABASE_STATE_KNOWN"
      },
...
```

**Comment by carols10cents** [comment]
This is moot now that there are no longer generation directories. 

I also had a server config file that pointed to a database directory for a database named `foo` where I had moved `rules.pb` to `old_rules.pb`. I then started up the server. The database named `foo` was in an error state, but the server was not in an error state. I could not run `database create foo` because `foo` already existed (in an error state), but I could create databases with any other name.

Please reopen if I'm missing something!
