### ISSUE TITLE
De-duplicate delete predicates

### ISSUE THREAD

**Issue by crepererum** [influxdata/influxdb_iox#2626]
Implement very simple delete predicate de-duplication (no fancy "is this predicate covered by another") and use it for:

- `CatalogChunk::add_delete_predicate`
- checkpoint generation (instead of [our hacky `Arc`-ptr comparison](https://github.com/influxdata/influxdb_iox/blob/155d5a5cce267a538e9666f9f41c9d19223ef0fc/server/src/db.rs#L1262-L1268))
- the persistence background worker (maybe)

**Comment by crepererum** [comment]
#2622 contains the first step towards this.

**Comment by NGA-TRAN** [comment]
This is a good task to pursue but we need to be extra careful here to avoid wrong results. I think we need define what a `predicate duplicate` is first. I think B is a predicate duplicate of A if A covers B. 

Predicate A covers predicate B means:
1. A's time range includes B's time range.
2. B's expressions include all A's expressions.

Examples:

- Predicate_1: 
  . time range:  [10, 40)
  . exprs: 
         . month = 3
         . city != "Boston"
         . temp = 70

- Predicate_2: 
  . time range:  [10, 40)
  . exprs: 
         . month = 3
         . city != "Boston"
         . temp = 70

- Predicate_3: 
  . time range:  [10, 40)
  . exprs: 
         . month = 3
         . temp = 70

- Predicate_4: 
  . time range:  [20, 50)
  . exprs: 
         . month = 3
         . city != "Boston"
         . temp = 70

- Predicate_5: 
  . time range:  [10, 40)
  . exprs: 
         . month = 3
         . city != "New Work"
         . temp = 70

- Predicate_1 covers Predicate_2 and vice versa (they are the same). Keep only one of them is enough.
- Predicate_3 covers Predicate_1 (same time range and B's expressions is less restricted) but not the opposite way around so we must keep Predicate_3 and can remove Predicate_1
- Predicate_1 does not cover Predicate_4, Predicate_4 does not cover Predicate_1 because their time ranges are only partially overlapped. We have to keep both of them.
- Predicate_1 does not cover Predicate_5, Predicate_5 does not cover Predicate_1 because their expressions are only partial overlapped. We have to keep both of them.

There may be more rules that I am not aware of

**Comment by NGA-TRAN** [comment]
And since this is an optimization, I have added it as an feature of the Epic #2395

**Comment by crepererum** [comment]
I was more thinking of "duplicate = exact same predicate", so I would postpone the coverage checks for now and keep it simple.

**Comment by crepererum** [comment]
We decided that we don't want/need this for now.
