### ISSUE TITLE
Flaky Tests on Apple Silicon

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb_iox#3197]
This morning an Apple Silicon builder ran into the following test failure:

```
failures:

---- field::test::incrementing_i64_that_resets stdout ----
thread 'field::test::incrementing_i64_that_resets' panicked at '`9` < `9` was false', iox_data_generator/src/field.rs:470:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    field::test::incrementing_i64_that_resets
```

Later on in the day, on my personal M1 machine I hit the following flaky test:

```
---- end_to_end_cases::management_api::test_chunk_access_time stdout ----
thread 'end_to_end_cases::management_api::test_chunk_access_time' panicked at '2021-11-23 16:11:31.601839 UTC 2021-11-23 16:11:31.601839 UTC', influxdb_iox/tests/end_to_end_cases/management_api.rs:1521:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

https://github.com/influxdata/influxdb_iox/blob/30ac22e3b78b43be70fff80c60af48e1a5ee144d/influxdb_iox/tests/end_to_end_cases/management_api.rs#L1520-L1523

In both cases the tests failed when asserting an explicit order between two values that were equal.

**Comment by tustvold** [comment]
I think these are separate issues - I think `incrementing_i64_that_resets` is just wrong. It is defining an incrementing metric that resets after 3 iterations and then asserting that the values after the reset is less than the value before (which isn't guaranteed because of the ranges). I will get a PR up to fix this.

The clock one I think is likely similar and I'll get a PR to fix this also
