### ISSUE TITLE
Use gRPC Error Model in gRPC Client

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#3251]
**Problem**

Currently within influxdb_iox_client we create an error enumeration for every method. This results in a huge amount of largely copy-pasted error boilerplate. With exception to the flight API, the gRPC client is pretty much entirely error plumbing. 

Aside from all the standard reasons DRY is good, the sheer wall of error handling hides the fact some of it is wrong.

For example, `unload_partition_chunk` converts all responses with a `FailedPrecondition` status code as:

```
#[error("Cannot perform operation due to wrong chunk lifecycle state: {}", .0.message())]
    LifecycleError(tonic::Status),
```

This is wrong, as `FailedPrecondition` is also used to signify that the writer ID is not set.

**Proposal**

The designers of gRPC already spent invested a significant amount of effort into making meaningful error variants, the clients should be switched over to a single error enumeration with the following variants using the detail payloads found in `generated_types::google`

```
pub enum Error {
    FieldViolation(FieldViolation),
    InternalError(InternalError),
    AlreadyExists(AlreadyExists),
    NotFound(NotFound),
    PreconditionViolation(PreconditionViolation),
    QuotaFailure(QuotaFailure),
    MissingDetails(tonic::Code),
}
```

Aside from eliminating a large amount of boilerplate, this accurately reflects the error model sent over the wire, and therefore avoids the problem of drifting error mappings

**Comment by alamb** [comment]
From my perspective, as long as the details of the original message are not lost (aka what actually happened if an `InternalError` is returned) this sounds like an improvement to me

**Comment by domodwyer** [comment]
Totally up for using the google errors for the on-the-wire serialisation - standards! 🎉 

I think it'd be a big step backwards in usability for the end user of the client if the API client no longer mapped these errors to something semantically meaningful though. As an example, at the moment deleting a database presents an enumeration of possible outcomes:

```rust
        match client.release_database(name.into(), uuid).await{
            Ok(_) => ...
            Err(ApiError::DatabaseNotFound { .. }) => ...
            Err(ApiError::NoServerId) => ...
            Err(ApiError::InvalidUuid { .. }) => // Name matches, UUID does not ...
            Err(ApiError::ServerError { .. }) => ...
        }
```

Which is descriptive, concise and an absolute treat to use and programatically match on! If these error types were removed, we'd have to match against the entire set of possible google errors, and pick apart each one and match on the types & strings inside them:

```rust
        match client.release_database(name.into(), uuid).await{
            // Error mappings are just examples obviously!
            Ok(_) => ...
            Err(ApiError::FieldViolation(f)) if f.field == "uuid" => // UUID was malformed
            Err(ApiError::FieldViolation(f)) if f.field == "name" => // Database name was invalid
            Err(ApiError::NotFound(f)) if f.resource_name == "name" => // Unknown error
            Err(ApiError::NotFound(f)) if f.resource_name == "uuid" => // The UUID was not found
            Err(ApiError::NotFound(f)) if f.resource_name == "name" => // The name was not found
            Err(ApiError::NotFound(f)) => // Unknown error
            Err(ApiError::PreconditionViolation(f)) if f.subject == "uuid" => // UUID did not match database name?
            // and so on... this is a request with only 2 fields!
        }
```

To me, that looks like it places a much higher burden on the end users to understand and maintain all the possible (string!) error values, and what each error type "means" so they can be mapped to semantically correct errors in order to take corrective action. 

Rather than making each client impl do all this brittle mapping, I think we should own it and do it once and for all - then everyone benefits from it. We're definitely in the best position to know what possible values are, and what they map to semantically compared to end users. If we're not being very good at mapping today we should put a bit of effort in to improve them - not rip them out and push the burden to the end user - I use this API client, and I'm happy to help!

**Comment by crepererum** [comment]
I agree w/ @domodwyer on the fact that more precise error types can be helpful to API users. I think some hybrid between the two could be helpful (e.g. replicate the google error types but parametrize them with a "subject/resource" enum).

**Comment by tustvold** [comment]
> match on the types & strings inside them

Is this not assuming that every single error variant is going to be handled independently? Aside from making for incredibly brittle code, I would have thought the vast majority of error variants will either simply be bubbled up, or handled based on their class? For example, I'm not sure how conductor could ever make use of a FieldViolation other than to report it to the user? Perhaps we could take an iterative approach and add error granularity as needed within conductor?

>  big step backwards in usability for the end user of the client if the API client no longer mapped these errors to something semantically meaningful though

My experience with granular error enumerations is they are an absolute pain to use, and bloat your codebase with enumerations just to allow you to propagate the error that was returned, or duplicating handling logic to handle the same class of error in multiple places. I'd say a single error enumeration for the client is significantly easier to use than 50 different ones...

> parametrize them with a "subject/resource" enum

Using enumerations instead of strings for subject and resource sounds like a good idea to me :+1:

**Comment by domodwyer** [comment]
> I'm not sure how conductor could ever make use of a FieldViolation

They were just illustrative examples of what it would look like :)

> I'd say a single error enumeration for the client is significantly easier to use than 50 different ones...

I guess we differ here then - I'd much rather have an enum that describes the possible error states (plus one for "unknown", obviously) and choose what they care about. So, using the example above, if they didn't care about all the other types of delete error:

```rust
        match client.release_database(name.into(), uuid).await{
            Ok(_) => ...
            Err(DbDeleteError::DatabaseNotFound { .. }) => // We care about this
            Err(_) => // All other errors are just "oh no it failed" :(
        }
```

If we have a big kitchen-sink style `Error` enum for loads of API endpoints it's going to contain lots of impossible variants depending on the API call. Would it make sense to have `AlreadyExists` as a possible error variant for `release_database()`? Probably not - how does the end user know what errors to expect and handle as legitimate?

I'm pretty sure we've discussed this more than once! I believe @pauldix 's position was something along the lines of "it should be easy as pie for end users" which makes sense to me - if it's creating an undue maintainability burden, let's chat about it - everything is tradeoffs!

**Comment by tustvold** [comment]
> if it's creating an undue maintainability burden

The maintenance burden is annoying but not the real issue here, the problem is that the mapping is fragile and oftentimes wrong because it is trying to graft a different error model on top of gRPC's error model.

> how does the end user know what errors to expect and handle as legitimate

The same way that a user knows what errors are going to arise from anything, a mixture of documentation and common sense... If you are creating an object and wish to handle the case where it already exists, you will write a test of that case see the error you get back, and handle it. This is no different from any programming interface without checked errors, which is pretty much all of them.

I'm not proposing we switch to just string error messages, simply we reduce the cardinality of the errors to the set already identified by the gRPC designers as being practical for end-users to actually correctly handle.

> I'm pretty sure we've discussed this more than once

Yes, and we reached the consensus to use the gRPC error model as we don't really have a choice in the matter. This issue is just proposing we stop trying to fudge around this

**Comment by domodwyer** [comment]
> the problem is that the mapping is fragile 

And it always will be which sucks! Converting from one domain to another that isn't one-to-one mapping is always difficult, but we're in the best position to handle it - pushing it to end users is just ignoring the problem.

> The same way that a user knows ......

I'll give you a nice example, perhaps that can help explain what is nice about the current model. When we introduced the release/acquire database change in IOx, the API semantics changed, and a new error condition was born - the "uuid does not match" error.

Because of the enumeration of possible error states, when the we (Conductor) upgraded the client the compiler said "hey! theres a new error condition to handle when you delete a database" and we could go in and choose to ignore it, map it to some generic "it's broken" error, or handle it explicitly. This is _nice_ for end users who don't necessarily know what behaviour has changed between IOx commits possibly months apart - the power to choose how granularly to handle errors is given to the client!

>  gRPC designers as being practical for end-users to actually correctly handle

They designed a generic error API, who's to say they don't intend clients to build application semantics on top of it? Punting back the gRPC errors is the equivalent of a HTTP API with a client that just gives back random status codes without converting it into useful semantic meaning - that's always a horrible API client :)

I don't get why the API client needs to follow a different API model from the code itself? When we call [`set_server_id()`](https://github.com/influxdata/influxdb_iox/blob/20da62eb87d416e46f9e568f9ec69f3ac7f9b07f/router/src/server.rs#L95) it returns a `Result<(), SetServerIdError>` with an error specific to the action, not a giant `IOxError` enum with all possible application error combinations that the caller has to somehow understand which variants might pop up.

**Comment by tustvold** [comment]
> the API semantics changed, and a new error condition was born - the "uuid does not match" error.

It's funny you use this as an example, as it is actually a client side error that was added to the client for when it gets back an invalid response :laughing:. The error model for all the error variants currently, is just matching on status code alone. This makes it actually worse than the raw gRPC error model, as the client isn't exposing or inspecting the error details at all! 

> I don't get why the API client needs to follow a different API model from the code itself

How about to make progress on this we faithfully, and accurately reproduce the wire error format. This would represent a concrete improvement over the status quo as currently the code is just wrong in many places. As we build up experience using the client we can then refine it, potentially adding an additional layer on top of this to translate errors for users. We need a faithful reproduction of the wire format in order to achieve this regardless of if there are subsequent layers on top to improve ergonomics?

**Comment by domodwyer** [comment]
Isn't that the same proposal as the original? I'd like very much to retain the errors for the client, for all the reasons above - I'm 1000% up for using the google types on the wire because it's much nicer so well up for that change! :)

**Comment by tustvold** [comment]
Had a good chat with @domodwyer yesterday, my takeaway was:

* Each method should return an error containing an enumeration of semantic errors that may occur from calling that endpoint - these will be what Conductor matches on for custom error handling behaviour
* Each method should also return the detailed error payload as it was on the wire - this will provide more context in the event of an error payload not split out as its own semantic error category (e.g. old client)
