### ISSUE TITLE
Update persistence info to the catalog

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#3564]
# Rationale
This is the third step of #3491 to update the catalog after a parquet file is created by the Ingester. We have to insert data into these table and remove the corresponding PersistingBatch in one transaction:
1. One row in `Parquet_File` table representing the newly created parquet file. Information in the IoxMetata will be used to insert this row.
2. N rows to `Processed_Tombstone` table in which N is the number of tombstones applied during persistence that creates the parquet file.

This means:
  - Insert into Parquet_File
  - Insert n-rows into Process_Tombstone
  - Delete PerstingBatch from the memory
  - Commit the Postgres inserts

**Comment by pauldix** [comment]
There's no need to hold the Postgres transaction open while removing the stuff from memory. I'd have a single function on the `Catalog` trait that is something like:

```
  asnc fn add_parquet_file_with_tombstones(&self, meta: &ParquetMeta, tombstones: &[Tombstone]);
```

Call that function which does the inserts within a Postgres transaction, but commits it all before returning, then remove the persisting batch from memory. 

The query API lets the query server specify a sequence_number to have all data greater than it. If the query server happens to pick up the new parquet file from the catalog and sends the request before the persisting batch has been removed from memory, it won't matter because the persisting batch will be excluded because of the sequence number.

**Comment by NGA-TRAN** [comment]
Thanks @pauldix . That makes it even simpler. Mainly 2 steps:
1. Update Postgres's parquet_file and processed_tombstone in one transaction using available function.
2. Remove the PersistingBatch
