### ISSUE TITLE
gRPC for ingester to send data to query servers

### ISSUE THREAD

**Issue by carols10cents** [influxdata/influxdb_iox#3616]
This issue is for implementing the gRPC API in ingester that will send `SnapshotBatch`es and `PersistingBatch` to the query servers.

From the design doc:

> ### Ingester Query API
> The API that ingesters expose to the query servers is fairly simple. More complex query processing should be pushed to the query servers to minimize load and potential for problems in the ingestion pipeline.
>
> This pushes projection and filtering to the ingester leaving any grouping, deduplicating, or sorting to the querier.
>
> This API can be Arrow Flight, but with a payload for `doGet` that passes a serialized `struct` with the following information:
>
> ```rust
> struct IngesterQueryRequest {
>   // we can lookup in memory by the table
>   table: String,
>   // only select the columns we care about
>   columns: Vec<String>,
>   // start time of the query
>   min_time: i64,
>   // end time of the query
>   max_time: i64,
>   // predicate for filtering
>   predicate: Option<Predicate>,
>   // optional to only return rows with 
>   // a sequence number > than this
>   greater_than_sequence_number: Option<u64>
> }
> ```
>
> Any buffered data in the specified time range should be returned in unsorted Arrow `RecordBatch`(es). This should include any data that is in the middle of being persisted to Parquet, but hasn't yet landed there. This could also have data from multiple partitions, each of which should come in their own `RecordBatch`.
>
> The metadata of the returned `RecordBatch`(es) must include the last persisted `max_sequence_number` for this table and the `partition_id`.
> 
> If the request returns a `max_sequence_number` for this table greater than what the querier has cached or knows about, it will know that it must check the Postgres catalog for new Parquet files.
> 
> If the request is for a table that hasn't been written to since this ingester has been up, the response should be empty, but include the sequencer's `min_unpersisted_sequence_number` that it read at startup so that the querier will know if there are potentially any Parquet files that might need to be read.
> 
> If the table has been fully persisted and evicted and no additional data has arrived, then the response should be an empty `RecordBatch` with metadata of the last persisted `max_sequence_number` so the querier will know whether to go lookup additional Parquet files.
>
> The ingester health API should include its Kafka lag time so that queriers can choose to query the ingester mirror that is most caught up to the edge (or at least know how stale their results might be).

**Comment by NGA-TRAN** [comment]
Since we split data into different types of batches in [DataBuffer](https://github.com/influxdata/influxdb_iox/blob/ac247e4de5396a68e8268ceec65f611a9a762878/ingester/src/data.rs#L137) and the `tombstones` only apply to data created before them, the actual data structure to send to the Querier will include `a vector data batches`, each batch includes:

1. A RecordBatch of actual data
2. A vector of Tombstones
3. max_sequence_number

The reason we need to send a vector of batches because their tombstones are different.

There will be different tasks to create those batches from the `DataBuffer`'s buffer, snapshots, and persistng, and deletes

**Comment by NGA-TRAN** [comment]
We need two grpc APIs: one to accept request, `IngesterQueryRequest`, and one the send the back the data

**Comment by NGA-TRAN** [comment]
An extra note is we need to verify if the tombstones are coupled with the data batches correctly. If we want to not couple them, we need to store `created_tome` with the tombstones to know which batch needs to apply the tombstones

**Comment by pauldix** [comment]
In the code I have to ingest deletes (#3533), Tombstones are added to every partition that happens to be open at that time. Although I'm not checking that the time range matches, I'm just blindly putting it in there right now. But from a sequence number perspective, it definitely applies. Although I realize just now that it should be changed so that the buffer gets snapshotted and the tombstone applies to the snapshot and not any data arriving after the delete. I'll log an issue for that.

So tombstones need to be associated with potentially many record batches, but there are other record batches (those that come in after the delete) that wouldn't have the tombstone applied.

**Comment by carols10cents** [comment]
> We need two grpc APIs: one to accept request, `IngesterQueryRequest`, and one the send the back the data

@NGA-TRAN I'm confused about this; won't it be *one* gRPC API, not *two*, because the `IngesterQueryRequest` will be the request that the query service sends to the ingester, and the ingester will send back the data as the `IngesterQueryResponse` for that one API? Or am I missing something?

**Comment by NGA-TRAN** [comment]
@carols10cents : yes, it was my. I noticed and deleted it. There should be only one grpc API 😄

**Comment by carols10cents** [comment]
Whew! :)
