### ISSUE TITLE
NG Querier: Interface between querier and ingester

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#3996]
The goal of this ticket is to think about, and design, if appropriate, additional functionality to handle the potential timing gaps between the querier planning queries and asking the ingester for data

Once we have completed https://github.com/influxdata/influxdb_iox/issues/3988

We are worried about the scenarios such as:
1. The querier plans query based on the parquet files currently in the catalog
2. <-- here the ingester completes a new parquet file and drops from memory
3. The query starts executing
4. The query asks the ingester for input

Will the query miss the data that was in memory during planning but in parquet files once execution starts?

@tustvold notes that there may also be challenges with projection pushdown as all the tag columns are needed for deduplication but we might not know at planning time what chunks might overlap.

**Comment by NGA-TRAN** [comment]
Regarding point #2, we have a solution which is simple for the Ingester but more work for the Querier and may not be the best **performance** solution but we can try it first.

Beside data, the Ingester also sent metadata, [IngesterQueryResponseMetadata](https://github.com/influxdata/influxdb_iox/blob/9961efd702e54ece75418b0e92dd6e48c5a77679/generated_types/protos/influxdata/iox/ingester/v1/query.proto#L38),  back to Querier that include `parquet_max_sequence_number`. If this number greater than the max  you get from ParquetFiles, you have to update the catalog and read the latest data. I know this is a pain for Querier.

We can do the other way around that the Querier sends the max_sequence_number it has and the Ingester will send all data right after that but this will have it side effect:
1. The Ingester has to keep persisted data longer
2. If the Ingester cannot keep persisted data that long, it has to go to OS and read the data which we are trying not to do.

Thoughts? @pauldix

**Comment by NGA-TRAN** [comment]
And as an extra not, the sent-back metadata also includes `tombstone_max_sequence_number` which is the the sequence number of the latest tombstones in case you need to do the same. But as a reminder, all data sent back from the Ingester are already applied tombstones. The new tombstones should only be used for the parquet file data.

**Comment by alamb** [comment]
@NGA-TRAN  I need to think about exactly where in the planning process the querier asks the ingester for data

I think the `InfluxRPC` planner asks for chunks *before* calling `scan` on them (aka asks for chunks before we have predicates or projections to push down). 

Thus at least initially InfluxRPC won't be able to take advantage of projection and filter pushdown 🤔 

But I suppose we can then improve things over time.

**Comment by NGA-TRAN** [comment]
@alamb Since the Querier-Ingester API let the Querier to send predicates, the Ingester does filter data (aka predicate pushdown) already. I think we can make plan to union data reading from OS and Ingester.

**Comment by alamb** [comment]
@NGA-TRAN  the issue is that the InfluxRPC planner doesn't know the predicates (yet) when it asks for the chunks

**Comment by NGA-TRAN** [comment]
> the issue is that the InfluxRPC planner doesn't know the predicates (yet) when it asks for the chunks

This will be tricky. Another point is data you get from Ingester needs deduplicated in the Querier. I bet after you build this query plan, you will bring up many optimizations for both Ingester and Querier

**Comment by pauldix** [comment]
Every query that hits the querier should hit the ingester. This could happen before you even plan a query in the normal sense. So say a query comes in:
1. Querier looks at which tables are in the query to map which sequencers need to be requested
2. Querier makes request to the ingester requesting data for the table passing:
  1. The max parquet sequence number the querier knows about from the catalog 
  2. The predicate from the query (don't bother with projection pushdown for now)
3. Ingester processes the request and sends back filtered data
4. The querier wraps the result in chunk(s) for deduplication and planning with the other chunks and normal execution from here

My idea with having the querier send the sequence number is that the ingester could cache recently persisted parquet chunks in memory. If the request has a sequence number less than what is in the buffer, then the ingester knows to look in the cache for the extra data.

If it has it in the cache then it applies the filter and returns it as another chunk in the response. If it doesn't have it in the cache then it needs to indicate this in the response so that the querier will know to refresh the catalog to get the Parquet file that was persisted, but no longer in cache that the querier didn't know about (because its catalog was cached).

Even without these cached Parquet files in the ingester, we should be able to have multiple chunks come back in the response from the ingester because there could be data across more than one partition. Ideally those would be separated so that the planning on the querier side could take that into account on the chunks in the response.

You could also use this pre-plan phase to limit the number of chunks in consideration for the query. Rather than loading all chunk information from the catalog into memory, you could just ask the catalog for chunks in a given time range for the table. Then pass off those chunks and the chunks from the ingester for the normal planning and execution phase.

I'm assuming we'll have indexes on the parquet_file table that would make these kinds of lookups really fast.

**Comment by alamb** [comment]
Thanks @pauldix  -- this makes sense. I think we may need to rejigger some of the planning in the InfluxRPC planner (as how it handles predicates is a little funky and relies on the columns that are actually present in the chunks), but I think we can push that to the ingester eventually. 👍

**Comment by tustvold** [comment]
> 3. The max parquet sequence number the querier knows about from the catalog

What happens if this is older than what the ingester has in memory, does the ingester fetch the missing data from S3, return an error? I had presumed the querier would need to ask the ingester for its data first, and then construct the rest of the query based on its response?

**Comment by tustvold** [comment]
Another thing to perhaps consider is how this interplays with the compactor, I _think_ I remember reading something about the compactor only soft-deleting parquet files, but this would be critical to ensure the parquet files don't "disappear" part way through the query

**Comment by pauldix** [comment]
If the max sequence number sent by the querier is older than what the ingester has in memory, it indicates in the response the max_sequence number from its last persist operation. This tells the querier that its catalog is out of date and that the ingester response didn't include data for the parquet file it apparently doesn't know about. So the querier would have to make a catalog request to get the information about that parquet file so it can include it in the plan and fetch it if necessary.

The querier should always be sending the latest sequence number it knows about for a given table & sequencer. This is to ensure that if its catalog cache is stale for this table & sequencer, the ingester can inform it of that in the response. Or, if the ingester still has that parquet chunk in memory because it was very recently persisted, it can send that result back as well as inform the querier so it can process the query, but update its parquet cache in the background.

**Comment by alamb** [comment]
Here is a writeup of how sequence numbers work: https://docs.google.com/document/d/19fA0XtXHPBnBxB2yc6jFMu3cBnv1jsVpovbFL1NqVzc/edit#

**Comment by alamb** [comment]
I believe @crepererum  plans to write this up

**Comment by alamb** [comment]
After discussion with Nga, Dom, and Paul and evaluating what code currently exists on `main`, my plan is to do the following:

# Goal and Rationale for the plan:
1. Get into production ASAP -- which to me means use existing code as much as possible, and leave corner cases for follow on work. 
2. The one important scenario to prevent is when the same query is issued sequentially to the same querier and ingester  and one time it includes data and then a subsequent time does not have that data (b/c for example it was persisted and flushed from the ingester)

# Plan

1. Implement the "indirect snapshot" approach. The rationale for doing so is pragmatism / laziness as most of it is already written.
2. Change the response between querier and ingester so that max persisted sequence number is returned *per partition* (currently, [it is one per table -- see code](https://github.com/influxdata/influxdb_iox/blob/9886ff4/querier/src/flight.rs#L120-L121))
3. Use those numbers to detect when the querier's view of parquet files is inconsistent and error when this is the case
4. Add end to end tests 

The querier's view of parquet files can be inconsistent when:
1. Its cache is out of date (new parquet file was added for some partition that it hasn't seen yet)
2. The data organization has changed significantly since the ingester sent its data -- aka if new parquet files got inserted and compacted, etc

I assume we'll need to iterate on this approach over time, but I think this will result in a reasonable MVP that we can deploy to production quickly and has reasonable correctness properties

**Comment by NGA-TRAN** [comment]
Sounds good to me. Thanks @alamb

**Comment by alamb** [comment]
I would say this is basically done now so closing it down
