### ISSUE TITLE
Column service limit not enforced

### ISSUE THREAD

**Issue by domodwyer** [influxdata/influxdb_iox#4137]
The service limit validation added in #3807 does not protect the `ColumnRepo::create_or_get_many()` code path which is used to [insert the columns during schema validation](https://github.com/influxdata/influxdb_iox/blob/8e85846db6c2e16a6367eea3feb49fc12401ba1e/iox_catalog/src/lib.rs#L156).

This probably slipped by as the insert-many code path in the in-memory catalog [delegates to `ColumnRepo::create_or_get()`](https://github.com/influxdata/influxdb_iox/blob/8e85846db6c2e16a6367eea3feb49fc12401ba1e/iox_catalog/src/mem.rs#L567) and therefore hits the correctly limited code path.

The current catalog tests assert that the limits [can be updated](https://github.com/influxdata/influxdb_iox/blob/8e85846db6c2e16a6367eea3feb49fc12401ba1e/iox_catalog/src/interface.rs#L725-L739) but I guess we should have tests that assert the limit is reached too to try and help prevent behavioural divergence between the various impls.

**Comment by lukebond** [comment]
i think the fact it slipped by is because there isn't a limits test that touches the "create many" function. since the tests are in the interface and are called for both implementations, it would be picked up as long as the tests touches that function.

i've added a failing test locally but i'm unable to come up with a query that will do it.

the SQL for a single column creation is:

```
INSERT INTO column_name ( name, table_id, column_type )
SELECT $1, table_id, $3 FROM (
    SELECT max_columns_per_table, namespace.id, table_name.id as table_id, COUNT(column_name.*) AS count
    FROM namespace LEFT JOIN table_name ON namespace.id = table_name.namespace_id
                   LEFT JOIN column_name ON table_name.id = column_name.table_id
    WHERE table_name.id = $2
    GROUP BY namespace.max_columns_per_table, namespace.id, table_name.id
) AS get_count WHERE count < max_columns_per_table
ON CONFLICT ON CONSTRAINT column_name_unique
DO UPDATE SET name = column_name.name
RETURNING *;
```

this works by binding the table ID to the inner query and ensuring that inner query won't return a table ID if the insert would go over the limit.

this is tricky to replicate with the current "create many" SQL statement:

```
INSERT INTO column_name ( name, table_id, column_type )
SELECT name, table_id, column_type FROM UNNEST($1, $2, $3) as a(name, table_id, column_type)
ON CONFLICT ON CONSTRAINT column_name_unique
DO UPDATE SET name = column_name.name
RETURNING *;
```

the `UNNEST` there is taking three vectors of values and transposing them into tuples, each row containing an element of each vector. the fact that it's inserting for multiple tables complicates things.

i suspect there is a solution possible along these lines:
- create a map of type table ID -> `Vec<ColumnUpsertRequest>`
- create an SQL statement that is able to do it for one table, using something like the single create method but using the number of columns being inserted per table, i.e. `WHERE count_as_calculated_before + N < max_columns`
- craft an over-arching SQL statement grouped by table id that uses the above statement as an inner query

but i don't think my friday 4pm brain can get there right now. writing it up here for my future self, or in case someone else can do it.

**Comment by mkmik** [comment]
friday, brain fried day

**Comment by lukebond** [comment]
this works for inserting for one table only:

```
INSERT INTO column_name ( name, table_id, column_type )
  SELECT input.name, get_count.table_id, input.column_type FROM UNNEST(ARRAY['balls9','balls10'],ARRAY[2,2],ARRAY[0,0]) as input(name, table_id, column_type)
  LEFT JOIN (
    SELECT max_columns_per_table, namespace.id, table_name.id AS table_id, COUNT(column_name.*) AS count
    FROM namespace
    LEFT JOIN table_name ON namespace.id = table_name.namespace_id
    LEFT JOIN column_name ON table_name.id = column_name.table_id
    WHERE table_name.id = 2
    GROUP BY namespace.max_columns_per_table, namespace.id, table_name.id
  ) AS get_count(max_columns_per_table, namespace_id, table_id, count)
  ON input.table_id = get_count.table_id WHERE (count + 2) <= max_columns_per_table;
```

next i'll figure out how to do this for multiple tables in one statement :grimacing:
