### ISSUE TITLE
Port / test golang iox client to work with NG

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#4412]
https://github.com/influxdata/influxdb-iox-client-go, primarily written by @jacobmarble is based on IOx OG. The success criteria of this ticket is:

1. Research any changes needed in IOx NG to support the currently exposed API (e.g. maybe DROP DATABASE?)
2. Figure out how to run the iox-client-go tests against NG all in one mode (#4399 and make sure the tests pass

**Comment by carols10cents** [comment]
I've filed these issues in the Go client repo:

- https://github.com/influxdata/influxdb-iox-client-go/issues/22
- https://github.com/influxdata/influxdb-iox-client-go/issues/23

I think those are the only things really *needed* to get its tests passing and ready for OG removal.

I also think it would be nice to have [delete namespace/`DROP DATABASE` functionality in IOx ](https://github.com/influxdata/influxdb_iox/issues/4467)so that tests like these could clean up after themselves, but I don't actually see anywhere currently using that functionality in the Go client.
