### ISSUE TITLE
build failed with `error[E0554]: #![feature] may not be used on the stable release channel`

### ISSUE THREAD

**Issue by duanshuaimin** [influxdata/influxdb_iox#459]
latest version 
os: osx
error[E0554]: `#![feature]` may not be used on the stable release channel

**Comment by alamb** [comment]
Thanks @duanshuaimin  

I think you need to ensure that you are using a nightly toolchain (not the stable release). We are using nightly to keep in sync with Apache arrow. 

What version does `cargo --version` report?

```
alamb@MacBook-Pro:~/Software/influxdb_iox$ cargo --version
cargo 1.49.0-nightly (2af662e22 2020-11-12)
```

**Comment by alamb** [comment]
FWIW @GregBowyer is actively trying to help us get to the point where we can use Rust stable 💯  (see https://github.com/influxdata/influxdb_iox/issues/115#issuecomment-728869007 et al for more details)

**Comment by duanshuaimin** [comment]
cargo 1.46.0

**Comment by shepmaster** [comment]
Chances are good that you have installed Rust through your system's package manager, instead of via [rustup](https://rustup.rs/). If rustup is active, it will automatically switch to the appropriate toolchain when you enter the iox directory.

It's almost guaranteed that you _won't_ be able to install the correct nightly version without rustup.

**Comment by duanshuaimin** [comment]
nightly it works well
