### ISSUE TITLE
Decide  IOx "Tier-1" platforms

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#462]
# Background

In this context, a tier-1 supported platform means an architecture and operating system combination "we will ensure that IOx builds and the rust unit and integration tests run on those platforms".

It does *not* necessarily imply that we will "support" the platform in the sense that if someone is running on one of these platforms and hits a bug that we would fix it.

# Platforms under consideration:

## Architectures:
* x86_64
* AArch32 (32 bit ARM, e.g. Rasperry Pi 1 and 2, I think)
* AArch64 (64 bit ARM)
* Apple M1 (AAarch64 based, I think)

## Operating Systems:
* Darwin / OSX
* Linix-64 bit
* Linux
* Windows

Note it is unclear if we should support with 32-bit linux w/ Arm (raspian) as a potential "edge" target

# Definition of done:
1. Finalize the list of supported platforms (arch and OS) above (with Paul and product??)
2. File ticket(s) to add the necessary testing / CI for those platforms to keep them at tier-1 status

**Comment by alamb** [comment]
@danxmoran brought my attention to the following crate if / when we embark on ARM/ other platforms: https://github.com/rust-embedded/cross

**Comment by danxmoran** [comment]
Following up on the above, I was able to get `cross` working to test static ARM builds for flux on my macbook. The hurdles I hit were related to `cross`'s use of Docker:
1. If you depend on any system libraries that aren't packaged in the default `cross` images, you'll need to maintain a custom `Dockerfile` per-arch for the tool to build / test within.
2. The tool mounts your crate at the root of the Docker image. If you have any build logic that depends on files from a parent directory of your crate, you'll get failures (hit this in flux since the Rust code is in a subdirectory of the whole project).

**Comment by domodwyer** [comment]
I've had good success building statically linked / musl builds with cross before - it works really well! We should be able to add this as part of the CI process I believe.

**Comment by domodwyer** [comment]
We should factor in support for SIMD when deciding on supported architectures - we lean on it heavily and it will significantly affect performance. 

The simd library has a list of architectures it compiles against, but from my quick scanning it isn't clear if all operations are fully vectorised or if there's any "polyfills" that fall back to scalar functions: https://crates.io/crates/packed_simd_2
