### ISSUE TITLE
Ingester & Compactor: need more metrics

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#4838]
# Rationale
The [Grafana Compactor Dashboard](https://grafana.prod01-eu-central-1.aws.influxdata.io/d/z7-FhLsnk/compactor?orgId=1&from=now-1h&to=now) has useful information but we still need more information to know exactly what is going on in the Compactors. Below is a growing list of information we need to look into daily/hourly to understand the health of the Compactors. The goals is to have the list added in Compactor dashboard(s). One big question is can we integrate results of SQL from our catalog directly without going through metrics coding?

- [ ] OOMs: when each of happens and on which compactor. How many times in the last n hours
- [ ] Number of partitions (this can be extended to number of orgs, namespaces, tables, columns, parquet files, ...). AND Number of partitions assigned to each compactor.
       TODO: Ticket to do background loop and get the following numbers. The SQLs just show what the results should look like. In the code, we can have different queries and extra code to achieve the same output with better performance.
    ```SQL
   -- number of tables
   select count(id) as total_table_count from iox_catalog.table_name;
  -- number of tables without partitions
   select count(distinct t.id) as table_without_partitions from iox_catalog.table_name t where not exists (select p.table_id from iox_catalog.partition p where p.table_id = t.id);
  -- number of tables per compactor
   select floor(s.kafka_partition/25) as compactor, count(distinct t.id) as table_count 
   from iox_catalog.table_name t, iox_catalog.sequencer s, iox_catalog.partition p 
   where p.table_id = t.id and p.sequencer_id = s.id group by compactor;
  -- number of partitions
  select count(*) total_partition_count from iox_catalog.partition;
  -- number of partitions without parquet files. This can be removed after we enforce: partition must have parquet files
  select count (distinct p.id) partitions_without_parquet_files 
  from iox_catalog.partition p   
  where not exists (select pf.id from iox_catalog.parquet_file pf where p.id = pf.partition_id);
  -- number of partitions per compactor
  select floor(s.kafka_partition/25) as compactor, count(distinct p.id) partition_count 
  from iox_catalog.sequencer s, iox_catalog.partition p 
  where p.sequencer_id = s.id group by compactor;
  -- number of partitions without parquet files per compactor. This can be removed after we enforce: partition must have parquet files
  select floor(s.kafka_partition/25) as compactor, count(distinct p.id) partitions_without_parquet_files 
  from iox_catalog.sequencer s, iox_catalog.partition p 
  where p.sequencer_id = s.id and not exists 
         (select pf.id from iox_catalog.parquet_file pf where p.id = pf.partition_id)  
  group by compactor;
   ```
- [ ] Number of distinct partitions each compactor compacts today
   ```SQL
   -- for all compactors
   select count (distinct pf.partition_id) today_compacted_partitions 
   from iox_catalog.parquet_file pf 
   where date(to_timestamp(pf.created_at/1000000000)) = current_date and pf.compaction_level = 1;
   -- per compactor
   select floor(s.kafka_partition/25) as compactor, count (distinct pf.partition_id) today_compacted_partitions
   from iox_catalog.sequencer s, iox_catalog.partition p, iox_catalog.parquet_file pf 
   where date(to_timestamp(pf.created_at/1000000000)) = current_date 
      and pf.compaction_level = 1 and pf.partition_id = p.id 
      and p.sequencer_id = s.id group by compactor;
   ```
- [ ] Number of files each compactor compacts the last n hours/minutes. --> See if Compactors are really working
    . TODO: Use available metrics. Just need to modify dashboard
- [ ] Number of ingested files vs number compacted level-0 files each compactor handles the last n hours/minutes --> See if Compactors catch up well with the Ingesters
    . TODO: 
         . Step 1: Use available metrics on Ingester (level-0 files) and Compactor (all level-0 and level-1 files) and add/modify dashboard to show/compare them.
         . Step 2: Ticket #4901 to create a new metrics to count compacted level-0 files only and use this new metrics instead

- [ ] Number of hot partitions (aka latest partitions) of more-than-one small files that are not compacted at all 
      . --> Investigate to see if there are starving issues?
      . --> Our goal is small and contiguous non-overlapped files should be compacted in a larger config size file
   ```SQL
   select count (distinct pf1.partition_id) 
  from partition p, parquet_file pf1, parquet_file pf2 
  where p.id = pf1.partition_id 
    and pf1.partition_id = pf2.partition_id and pf1.id != pf2.id  -- at least 2 different files of the same partition
    and pf1.to_delete is null and pf2.to_delete is null
    and (pf1.compaction_level = 0 or pf2.compaction_level = 0)  -- at least one newly ingested file
    and pf1.file_size_bytes + pf2.file_size_bytes < MAX_FILE_SIZE -- MAX_FILE_SIZE is a config value
    and p.partition_key = cast(current_date as text);   -- hot/latest partition
   ```
- [ ] Number of cold partitions with overlapped parquet files --> Our goal is cold partitions (aka not-the-latest partitions) should only include non-overlapped files
   ```SQL
   select count (distinct pf1.partition_id) 
   from partition p, parquet_file pf1, parquet_file pf2 
   where p.id = pf1.partition_id  
     and pf1.partition_id = pf2.partition_id and pf1.id != pf2.id  -- at least 2 different files of the same partition
     and pf1.to_delete is null and pf2.to_delete is null
     and pf1.min_time >= pf2.min_time and pf1.min_time <= pf2.max_time  -- overlapped files
     and p.partition_key < cast(current_date as text);   -- cold/old partitions
   ```
- [ ] Number of partitions without parquet files --> Invesigate why. The time to have empty partitions should be short because its parquet files should be created soon after a partition is created.
       . TODO: Ticket #4900 to  make create-partition in the same transaction with the create-first-parquet-file and prevent this from happening. The sort_key must be created with the parquet file and inserted with the partition

**Comment by NGA-TRAN** [comment]
I have added 4 more panels for 4 sets of SQLs https://github.com/influxdata/k8s-infra/pull/4049.

**Comment by domodwyer** [comment]
Me and @NGA-TRAN had a chat about metrics! These are my potentially indecipherable notes.

All metrics should be per-compactor (or at least per-shard) so we can identify which compactor is slow/healthy/broken/etc. Global view can be computed by summing across all compactors.

TODOs:
* Number of partitions per compactor - use a background task to poll & expose per compactor+shard
* Number of files in last N hours/mins - already exists, needs nicer graphing
* Number of ingested files vs number compacted level 0 - need to label compaction counter by shard and level, and ingester uploads by shard so we can contrast the two in a graph (per shard)

Undecided:
* Number of hot partitions needs compacting - this could be expensive, I will check the SQL from @NGA-TRAN 
* Number of cold partitions needs compacting - this will grow with the number of partitions (a large increase per day) and is going to be extremely expensive. We can't really run this on a dashboard.
* Number of partitions with small non-overlapped files - I will check the SQL to understand this better, but will also grow in cost as the number of partitions increases and might be prohibitively expensive to run from the dashboard.

Code changes:
* Number of partitions with parquet files but empty sort_key

Because we first create the partition in the ingester, and some time later, upload a parquet file to object store and then create a parquet file row. I assume we do this so we can embed the partition ID in the parquet file. This causes us to first create an empty sort key, and later, as the parquet file record is created, set the sort key on the partition. This leads to us having a partition entry with no sort key. Ideally we would uphold the invariant `a partition always has a non-empty sort key`.

* Number of partitions without parquet files

Similar to above, the non-atomic partition-creation-then-parquet-file-creation means we can observe intermediate state (a partition with no parquet files).

If we change the ingester to avoid creating partitions with no parquet files, and assert the sort key is always non-empty, we can statically assert that neither of these situations will happen. Because they can't happen, we can avoid having to query for them from a dashboard too 🎉

**Comment by carols10cents** [comment]
> All metrics should be per-compactor (or at least per-shard) so we can identify which compactor is slow/healthy/broken/etc. Global view can be computed by summing across all compactors.

Wouldn't only per-shard be more useful because shard/sequencer assignment to compactor can potentially change if we add more sequencers or compactors? Then in the dashboard, you could choose the set of sequencers that are/were assigned to the compactor you're interested in?

> TODOs:
>
> *   Number of partitions per compactor - use a background task to poll & expose per compactor+shard

Does this need to be a new background task or is this something that could happen in the [`run_compactor` loop](https://github.com/influxdata/influxdb_iox/blob/80b6c5c82fc69893122ef0380b98167ede005392/compactor/src/handler.rs#L177-L178)? And is this the total number of partitions per sequencer (shard) ID? The number of partitions that need compaction? The number of partitions that have been compacted?

> Number of ingested files vs number compacted level 0 - need to label compaction counter by shard and level, and ingester uploads by shard so we can contrast the two in a graph (per shard)

I believe the compaction side of this is [this issue and it's already done](https://github.com/influxdata/influxdb_iox/issues/4901#issuecomment-1179151794). From what I can tell, it looks like the ingester side needs to be done?

**Comment by NGA-TRAN** [comment]
@carols10cents 
> Wouldn't only per-shard be more useful because shard/sequencer assignment to compactor can potentially change if we add more sequencers or compactors? Then in the dashboard, you could choose the set of sequencers that are/were assigned to the compactor you're interested in?

Yes, per shard is good but we need to be able to map them to a specific the compactor easily because the OOM and CPU usage is per compactor

> Does this need to be a new background task or is this something that could happen in the [run_compactor loop](https://github.com/influxdata/influxdb_iox/blob/80b6c5c82fc69893122ef0380b98167ede005392/compactor/src/handler.rs#L177-L178)? And is this the total number of partitions per sequencer (shard) ID? The number of partitions that need compaction? The number of partitions that have been compacted?

It can happen anywhere as long as it does not heavily affect the compaction performance. And yes, number of partitions per shard. We want all: total partitions, partitions chosen to compact, partitions have been compacted

>>  Number of ingested files vs number compacted level 0 - need to label compaction counter by shard and level, and ingester uploads by shard so we can contrast the two in a graph (per shard)

> I believe the compaction side of this is https://github.com/influxdata/influxdb_iox/issues/4901#issuecomment-1179151794. From what I can tell, it looks like the ingester side needs to be done?

I need too look into the Ingester but I think the Ingester should have this counter already

**Comment by carols10cents** [comment]
> > Does this need to be a new background task or is this something that could happen in the [run_compactor loop](https://github.com/influxdata/influxdb_iox/blob/80b6c5c82fc69893122ef0380b98167ede005392/compactor/src/handler.rs#L177-L178)? And is this the total number of partitions per sequencer (shard) ID? The number of partitions that need compaction? The number of partitions that have been compacted?
> 
> It can happen anywhere as long as it does not heavily affect the compaction performance. And yes, number of partitions per shard. We want all: total partitions, partitions chosen to compact, partitions have been compacted

Ok, I've extracted this TODO item into its own issue that I think I can work on now: https://github.com/influxdata/influxdb_iox/issues/5081

**Comment by NGA-TRAN** [comment]
Close this. Most of them are done with recent PRs and a few no longer needed.
