### ISSUE TITLE
Lots of useless `write buffer aggregator` tracing spans generated

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#4885]
__Steps to reproduce:__
Run IOx configured to send spans to jaeger

__Expected behaviour:__
Only data that was actually traced is in jaeger so that I can find interesting traces

__Actual behaviour:__

Jaeger contains lots of spans that contain `write buffer aggregator` and nothing else:

![Screen Shot 2022-06-16 at 2 22 00 PM](https://user-images.githubusercontent.com/490673/174139472-b08df057-a70c-4abe-a91d-48d845eeef0a.png)

**Comment by alamb** [comment]
@crepererum / @domodwyer   any ideas on this one? It appears to come from https://github.com/influxdata/influxdb_iox/blob/9122850fe505bd5ac8d2bda4ef602987f437f78a/write_buffer/src/kafka/aggregator.rs#L87  / https://github.com/influxdata/influxdb_iox/pull/3676

**Comment by crepererum** [comment]
That's the way tracing aggregation works:

1. multiple HTTP requests come in
2. they get fed into the write buffer (after some processing)
3. write buffer aggregates writes: the only way to express aggregation is by creating a new span and linking it to the ones in step 1
4. write buffer sends span data over Kafka
5. ingester picks that up, links its tracing information to it
6. magic: you can now follow the tracing data in ingester all the way back to the HTTP requests in step 1

The reason that the link information in your screenshots isn't really shown is because of https://github.com/jaegertracing/jaeger-ui/issues/662 (IIRC).

**Comment by alamb** [comment]
@crepererum  I guess what I am observing is that the content in Jaeger of the new spans created in the write buffer aggregator is both:
1. Not useful itself
2. Seems to overwhelm traces with actual information

What would you think about it if I did not create a new Root span in the "write buffer aggregator"?

**Comment by alamb** [comment]
What I really want is useful IOx traces we can see in jaeger. If you think the single spans from "write buffer aggregator" contain useful information then keeping them makes sense to me. It just isn't clear to me how to use what is in Jaeger today


> TBH I would rather go and fix Jaeger than loosing the tracing information.

That would be fine too. I didn't read the ticket in any detail, but it seems to have been opened for more than a year.

**Comment by crepererum** [comment]
Let be provide some more background:

1. Internally, IOx uses the OpenTelemetry data model. So for aggregations[^1] we create a new span out of thin air and link it to the input spans.
2. For Jaeger there is an [official way to export links](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk_exporters/jaeger.md#links).
3. The Jaeger backend also accepts this.
4. However -- and this is what the [upstream ticket ](https://github.com/jaegertracing/jaeger-ui/issues/662) is about -- the Jaeger frontend/UI currently does NOT visualize this information.

Now the somewhat sad thing is that Jaeger doesn't seem to receive much contribution recently. I guess this is because many users use either some all-in-one solution that isn't solely focused on tracing (but also handles metrics and logs) or just use whatever their cloud provider manages.

That said, I think there might be some workarounds (some users in the upstream ticket mention that) and looking at our traces I also think that some links/relationships are broken. I'll investigate that.

[^1]: Deaggregations would work in the same way.

**Comment by alamb** [comment]
The only way I "consume" (look at) traces is via the Jaeger frontend / UI -- thus from my perspective if Jaeger doesn't visualize something it is basically invisible (and thus not useful to me)

**Comment by alamb** [comment]
this code has been deleted -- https://github.com/search?q=repo%3Ainfluxdata%2Finfluxdb_iox%20write%20buffer%20aggregator&type=code so I don't think this issue is relevant anymore
