### ISSUE TITLE
Implement full compaction for cold partitions

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb_iox#5330]
A "cold partition" is one that hasn't received a new L0 parquet file for some period of time. Currently, we partition data by 24h, but in the future we will give users the ability to partition data on different intervals per table. So this cold period should be derived from whatever the partition duration is.

Once a partition is cold, the compactor should attempt to do a "full compaction" in which the goal is to have:
1. Only L1 files (all non-overlapping in time)
2. As few L1 files as possible with the files not going over some configured max size (doesn't have to be exact, just roughly within the range)

Currently, hot partitions that receive many writes will end up having many L1 files. This is due to the configuration of the compactor, which creates smaller non-overlapping L1 files to avoid unnecessary write amplification while a partition is actively receiving writes.

Once a partition is cold, these non-overlapping L1 files should be combined into fewer, larger L1 files. This is in addition to compacting any remaining L0 files that haven't yet been compacted.

**Comment by carols10cents** [comment]
@pauldix One thought I'd like to validate and one question:

## Supporting future configuration of partition interval per table

> A "cold partition" is one that hasn't received a new L0 parquet file for some period of time. Currently, we partition data by 24h, but in the future we will give users the ability to partition data on different intervals per table. So this cold period should be derived from whatever the partition duration is.

I don't think there's anything useful to do right now to support this future use case; documenting my reasoning and the current state of the code:

- Partitioning is currently configured using this hard-coded, global `PartitionTemplate` in the router, expressed as a time format, not a number of hours: https://github.com/influxdata/influxdb_iox/blob/b820f69b0552ad4225044d84300edcae4301056d/ioxd_router/src/lib.rs#L197-L199
- The number of hours that determine whether a partition is selected as a "cold" compaction candidate is currently configured using this hard-coded, global 24 value: https://github.com/influxdata/influxdb_iox/blob/b820f69b0552ad4225044d84300edcae4301056d/compactor/src/compact.rs#L325
- That number of hours is passed to a catalog function, so if in the future the time period for partitioning is stored on a table record in the catalog, this query could join to the record in the catalog instead of using a parameter: https://github.com/influxdata/influxdb_iox/blob/b820f69b0552ad4225044d84300edcae4301056d/iox_catalog/src/postgres.rs#L1720-L1736

## Compacting both level 0 and level 1

> Once a partition is cold, these non-overlapping L1 files should be combined into fewer, larger L1 files. This is in addition to compacting any remaining L0 files that haven't yet been compacted.

Should combining L1 files into fewer L1 files be done after compacting remaining L0 files with any overlapping L1 files, in two distinct steps (which might lead to immediately recompacting some L1 files),

OR

Should combining L1 files into fewer L1 files be done at the same time as compacting remaining L0 files, which potentially gets us back into doing complicated algorithms to create non-overlapping groups? Or am I overthinking this? The simplest cold compaction algorithm I can think of is:

- Select all files for this partition, both L0 and L1
- Combine them all
- Split them into non-overlapping files based on the configuration parameter for approximate desired size of the final parquet files

which might recompact more than is strictly necessary? Would this use up too much memory? Am I missing anything?

**Comment by pauldix** [comment]
For the duration I don't think there's anything to do now. I'd reduce the cold period to something like 8h rather than 24h. In the future when we enable user configurable partitioning, I would expect the duration part of that partitioning to be part of the Table in the Catalog.

Ideally you'd compact the L0 files at the same time as the L1 files. I think your simple algorithm is the right way to go, but the question is if this is going to blow out the memory if there are many files. This actually might be the case so maybe the better thing to do would be:

1. Compact L0 files using the normal mechanism
2. Organize the L1 files into groups based on size (they're all non-overlapping at this point so you can just loop through, selecting based on their size)
3. Run each group compaction

This way if you have 1,000 total L1 files of 4MB each, and we're looking for 100MB resulting files, we'd end up having 40 groups that can be compacted separately (at whatever level of parallelism we want).

**Comment by pauldix** [comment]
Oh, and one thing we'll have to do is to make sure we don't re-compact cold partitions that have already been fully compacted. Not sure what will be the best way to determine that one.

**Comment by carols10cents** [comment]
> This actually might be the case so maybe the better thing to do would be:
>
> 1. Compact L0 files using the normal mechanism
> 2. Organize the L1 files into groups based on size (they're all non-overlapping at this point so you can just loop through, selecting based on their size)

So step 1 is going to create more L1 files, do those get included in step 2 (and potentially immediately recompacted) or do they get excluded?

> Oh, and one thing we'll have to do is to make sure we don't re-compact cold partitions that have already been fully compacted. Not sure what will be the best way to determine that one.

We can add a `fully_compacted` boolean to the partition records in the catalog?

**Comment by carols10cents** [comment]
Or we can reintroduce level 2?

**Comment by pauldix** [comment]
Step 1 is going to create more L1 files, which should be included in step 2. I think reintroducing level 2 is a good idea for representing full compaction. Then the compactor will only ever look for L0 files during hot partitions and L0 + L1 files when looking for cold partitions.

But I'd expect the compaction to be a bit different if an L0 file comes into a fully compacted partition. At that point the compactor could compact the L0 file with overlapping L2 files to create new L2 files.

**Comment by carols10cents** [comment]
Ok so currently, selecting partitions that need cold compaction is: https://github.com/influxdata/influxdb_iox/blob/44d72b2e94e7a6d2c81592ed0313cc7649b6a665/compactor/src/compact.rs#L303-L308

and the candidates are sorted by the number of level 0 files they have, more level 0 files giving that candidate a higher priority.

It sounds like this needs to change to:

```diff
     /// Return a list of partitions that:
     ///
-    /// - Have not received any writes in 24 hours (determined by all parquet files having a
+    /// - Have not received any writes in 8 hours (determined by all level 0 and level 1 parquet files having a
-    ///   created_at time older than 24 hours ago)
+    ///   created_at time older than 8 hours ago)

-    /// - Have some level 0 parquet files that need to be upgraded or compacted
+    /// - Have some level 0 or level 1 parquet files that need to be upgraded or compacted

-    /// - Sorted by the number of level 0 files descending
+    /// - Sorted by the number of level 0 files + number of level 1 files descending
```

And if a partition only has level 2 files, it won't be selected by this code.

Does that sound right?

**Comment by carols10cents** [comment]
> we're looking for 100MB resulting files

I'm also going to read this as "the default for the configuration option should be 100MB".

**Comment by pauldix** [comment]
> I'm also going to read this as "the default for the configuration option should be 100MB".
I believe we already had this setting somewhere in the compactor settings? We can probably use that same one. Or we can have a separate one if we don't.

**Comment by carols10cents** [comment]
We do have `--compaction-max-desired-size-bytes` aka `max_desired_file_size_bytes`: https://github.com/influxdata/influxdb_iox/blob/0ccefa0d0c479e0f55f345e36f2328f9b3de4d52/clap_blocks/src/compactor.rs#L45-L54

which is used along with `percentage_max_file_size` and `split_percentage` to try to split level 1 files to be some percentage smaller than `max_desired_file_size_bytes`: https://github.com/influxdata/influxdb_iox/blob/0ccefa0d0c479e0f55f345e36f2328f9b3de4d52/compactor/src/parquet_file_combining.rs#L80-L89

but in your example here:

> This way if you have 1,000 total L1 files of 4MB each, and we're looking for 100MB resulting files, we'd end up having 40 groups that can be compacted separately (at whatever level of parallelism we want).

it sounds like you expect to have L1 files of one size and want to combine them into a much larger size, so it seemed like these values should be able to be set independently.

Or am I making too many assumptions?

**Comment by pauldix** [comment]
I think it's that we ultimately want a max file size (represented in L2) and that along the way we should be creating smaller files that are some percentage of those. So `max_desired_file_size_bytes` would be the L2 size.

**Comment by carols10cents** [comment]
Aha, I see. I'll make that change!

**Comment by carols10cents** [comment]
Reopening this because we actually disabled full compaction to reduce the complexity.

**Comment by carols10cents** [comment]
The compactor has been redesigned; the context this issue captures isn't relevant anymore.
