### ISSUE TITLE
Log partitions and tables that are too big to compact 

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#5458]
# Rationale

In #5457, if we cannot compact at least 2 files together, we will skip compacting that partition. This ticket is to log that partition and its table in a new table in our catalog.

Things to consider:
 1. We do not want to log the same info
 2. Do we want to use the info in this new table to eliminate candidates?

**Comment by pauldix** [comment]
Yes, the problem with skipping partitions to compact is that they will then come up every time we do candidate selection. So ideally we'll use this table for two purposes:
1. To have a persistent log of partitions we've skipped compaction on so that we can follow up with an investigation
2. To have a set of partitions that need to be excluded from consideration

Ideally as the investigation happens and the issues get cleared up, we'll be able to trim this table. That way we won't have an ever increasing set of partitions to ignore.

**Comment by NGA-TRAN** [comment]
Compactor 0 and 3 hit this `skipped; over memory budget`. We should do this ticket soon
