### ISSUE TITLE
test: Add new flags to use in local AWS object_store integration testing

### ISSUE THREAD

**Issue by brandonsov** [influxdata/influxdb_iox#552]
__Use case:__
Allow a way to trigger local mock services like AWS 

__Proposal:__
`IS_LOCAL` boolean environment variable added and `AWS_LOCAL_ENDPOINT`. Unit tests will fetch `AWS_LOCAL_ENDPOINT` value and if `IS_LOCAL`=true and use a Custom Region for testing

__Current behaviour:__
Tests pull actual AWS credentials for local testing

__Desired behaviour:__
Allow local integration tests to use this custom region instead of actual AWS credentials 

__Alternatives considered:__
- I proposed adding an `IS_LOCAL` flag in case there are other use cases for that environment variable. To minimize the scope of this change, could restrict local usage to check if `AWS_LOCAL_ENDPOINT` exists then perform local operations with that. An issue I see with this is accidentally leaving `AWS_LOCAL_ENDPOINT` supplied which, personally, I find harder to deal with compared to determining if an existing `IS_LOCAL` flag is set to `true` or `false`. 
- Instead of an `IS_LOCAL` environment variable flag, use a conditional compilation flag to represent going down the local path of code.

__Notes:__
The 5th down in "Questions and Remarks:" in https://github.com/influxdata/influxdb_iox/pull/536

**Comment by alamb** [comment]
I am not quite sure what “Allow a way to trigger local mock services like AWS” means

It sounds to me like this ticket may be suggesting better ways to configure AWS -- @brandonsov  can you please clarify?  The links for a [custom rusoto region](https://www.rusoto.org/regions.html) from https://github.com/influxdata/influxdb_iox/pull/536 doesn't seem to work anymore

My gut feeling is that any solution that aims to be a local version of AWS will be compaitible with their endpoints and configuration parameters as well -- perhaps rusto has evolved sufficiently since when this ticket was filed.

**Comment by crepererum** [comment]
I believe this is fixed by #3388.
