### ISSUE TITLE
Compactor (optimization): New cycle of cold compaction does not pick the partitions that have just got partially compacted

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#5755]
# Rationale

The function `most_cold_files_partitions` only selects partitions with `created_at` older than certain time (8 hours ago). However, if there are a lot of L-0 and we can only compact a part of them, there will be a lot of L-0 and L1 left for us to compact in the next cycles but we do not select that partition because that partition has new write of compacted files (L1) or new upgrade from L0 to L1 that update the `create_at` to the latest time. This will lead us to wait another 8 hours to continue compact this partition. And it repeats waiting for another 8 hours. It may take days/weeks for finish compacting this partition.

If the Compactors are catching up well, we do not have many L0s and do not have to worry about this. However, if for some reasons, a partition does not get compacted immediately (e.g. this can be the case if it needs more memory budget and we push it in the `skipped_compactions` table to wait for manual action), it will accumulate a lot of L0s and leads to this situation.

We need to think a way to continue compacting this partition.

Currently (2202.09.28), partition `1685212` is in exactly the situation. When I remove more partitions from the skipped_compactions , we will hit more

**Comment by NGA-TRAN** [comment]
More thoughts:

If the cluster does not get restarted/redeployed and interrupts the compaction process, all newly created L1 are then compacted to L2 which I think the case, the remaining L0s and L1s were still created long ago which still good for them to get picked the next cold compaction cycle.

If the cluster is  restarted/redeployed  after new L1s are created in the first step of cold compaction, these L1 will be new enough to make the partition not to get pick in the next cycle and has to wait for another 8 hours to get selected

**Comment by carols10cents** [comment]
Interesting. I think another way to think about this is how does the compactor tell between:

- New L1 files that are the result of a recent cold compaction cycle
- New L1 files that are the result of recent writes and a hot compaction cycle

**Comment by NGA-TRAN** [comment]
There are a few clear options:

1. Do nothing and let it eventually get compacted. The cons of this is if we need to query this partition, it either slow or we cannot even query them if the partition include a lot of small files and  the query needs to access all/most of them.
2. Add a column named `from_cold_compaction` in `parquet_file` table. This is the easiest implementation way but do we want to add another field in this already wide and frequently accessed table?
3. Make different level (e.g 101) for this. Most of the case, this level-101 will be treated the same as level-1. Only we do not consider its `created_at` time when select candidates for cold compaction. The cons of this is we need to change the implementation to treat 1 and 101 the same or different accordingly.

**Comment by pauldix** [comment]
The idea behind hot and cold compaction is all about when a partition is receiving writes from the normal ingest pipeline. While it is still receiving writes (i.e. producing new L0 files) it is in a "hot" state. After it stops receiving writes (no new L0 files getting created), it is in a "cold" state. For most of our users and customers, 4 hours is probably a long enough timer to mark that transition from hot to cold.

The point of having the two different states is that we want to avoid doing too much work while a partition is still hot and writes could come in for various points in time (thus overlapping with previously compacted data).

This could also be viewed on a sliding scale. The older a file is, the less likely it is to have new arriving data overlapping with it. For L1 files that don't overlap with each other, the goal is to combine them into larger L1 files so that the querier has fewer chunks to deal with. So as a file gets older, it becomes a more likely candidate to compact with its neighbors because it is less likely to be overwritten later by new data arriving that overlaps with it.

However, if we're only going to keep two discrete states of hot and cold, you could say the following:
1. A partition is cold if there are no L0 files (marked to_delete or otherwise) with a created_at time less than 4 hours ago.
2. Otherwise a partition is hot and L0 files should be compacted into L1.

The determination of hot vs. cold should have nothing to do with the L1 or L2 files. While a partition is hot we should have one type of compaction behavior. When a partition is cold we should aim to compact it into as few L1 or L2 files as possible (i.e. we should do a full compaction).

**Comment by NGA-TRAN** [comment]
@pauldix Good point. I think we will go with: 

- hot is having L0s created recently
-  cold is all L0s created N hours ago or no L0s at all but having L1s.
We will change the implementation to reflect this.

The reason we count L1s because we want to prioritize which partitions to get compacted first which I agree is just a part of the candidate prioritization, not candidate selection
