### ISSUE TITLE
Deduplicate data at read time

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#600]
The following two line protocol formatted data represent the same data (as tagset and timestamp is shared):
```
measurement tag=A field1=1.0 100
measurement tag=A field2=20.0 100
```

```
measurement tag=A field1=1.0,field2=20.0 100
```

However, IOx treats them differently when line protocol is written into the mutable buffer. Namely the first will be

```
tag | field1 | field 2 | timestamp
----+--------+---------+----------
A   | 1.0    |         | 100
A   |        | 20.0    | 100
```

And the second will be
```
tag | field1 | field 2 | timestamp
----+--------+---------+----------
A   | 1.0    | 2.0     | 100
```

The goal of this ticket is to make writes into IOx handle them as a single row

**Comment by pauldix** [comment]
Ideally this isn't based on tagset and timestamp, but based on whatever the primary key is set to be for the table. Because IOx will create new tables and new columns on write, the individual database configurations must have rules for what to use as the default primary key. The default would be tagset and `time`. The tricky bit is that as new tag columns are added, those become part of the primary key fora  table.

So once a table gets created, its primary key should be set to the tag columns and `time` for that first record written in. Then if they have records that come in that create new tag columns, the primary key for the table should be updated to include that new column.

**Comment by alamb** [comment]
An alternate implementation would be to resolve these at read time

**Comment by alamb** [comment]
Proposed design document: https://docs.google.com/document/d/1iD_Q2kpC2Kopo4DEq_Oym4jEvaz-SfUUVmr_dpMcikc/edit#

**Comment by NGA-TRAN** [comment]
# CheckList
- [x] Code up full deduplicate foundation -  #1635 
- [ ] Add primary key in `Schema`
- [ ] Implement is_sorted for DbChunk (or PartitionChunk)
- [ ] Implement is_sorted for DbChunk (or PartitionChunk)
- [ ] Add UnionExec inside function build_scan_plan  -- Nga
- [ ] Implement split_overlapped_chunks function
- [ ] Implement DeduplicateExec needed in the 2 functions below
- [ ] Implement build_deduplicate_plan_for_overlapped_chunks function -- Nga
- [ ] Implement build_deduplicate_plan_for_chunk_with_duplicates. -- Nga
