### ISSUE TITLE
Router rejects data outside the retention period

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#6027]
# Rationale

This is a task of #3053. If client loads data outside of retention period (time < now - namespace's retention_period_nano), router will return a 400 error

**Comment by NGA-TRAN** [comment]
@domodwyer: I can start working on this now. If you think a place I should start or look into first, can you link them here?

**Comment by domodwyer** [comment]
This should be implemented as a [`DmlHandler`](https://github.com/influxdata/influxdb_iox/blob/c902f331780bd5e5488424cefbf12bf86aedb1f2/router/src/dml_handlers/trait.rs#L35-L76) that sits at the start of the [chain of handlers](https://github.com/influxdata/influxdb_iox/blob/c902f331780bd5e5488424cefbf12bf86aedb1f2/ioxd_router/src/lib.rs#L270-L282) (before the partitioner):

https://github.com/influxdata/influxdb_iox/blob/c902f331780bd5e5488424cefbf12bf86aedb1f2/router/src/lib.rs#L41-L58

Some notes about the implementation:

* The checker will need to use a cache of namespace ID -> retention period so that we do not have to query the catalog for every write (this is a must). 

* I'd strongly advise we pre-warm this cache at startup with a single query to list all (or the most recent N, if all is too many) retention periods. [This is what we do for the namespace schema cache](https://github.com/influxdata/influxdb_iox/blob/c902f331780bd5e5488424cefbf12bf86aedb1f2/ioxd_router/src/lib.rs#L197-L199) and it significantly reduces the catalog load / eliminates high request latency at startup.

* Ideally we would construct this as a `DmlHandler` that calls into an abstract read-through cache behind a trait, similar to what we do with the namespace cache:

https://github.com/influxdata/influxdb_iox/blob/c902f331780bd5e5488424cefbf12bf86aedb1f2/router/src/namespace_cache.rs#L15-L28

This would let us test the validation code easily / without a mock catalog (which involves a lot of boilerplate / fragile code to set up the catalog state), and lets us compose together a catalog implementation, a cache decorator that wraps the catalog implementation, a sharded map to reduce lock contention (definitely optional), etc.

As always I am happy to help / pointers / review / chat on zoom :pray:
