### ISSUE TITLE
Filter data outside the retention period at query time

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#6028]
# Rationale

This is a task of #3053. 
Querier will filter data outside the retention period by adding this predicate in all queries
    time < now - retention_period_nano of the table

**Comment by alamb** [comment]
I will take a shot at this later this week

**Comment by alamb** [comment]
# High level proposal

My proposal is to model the retention period using a `DeletePredicate` added in the `querier` and then passed the `iox_query` crate

So if we have a retention of 1 week, the querier will effectively add a predicate like

```sql
where time < now() - interval '1 week'
```

To any chunk that contains rows outside the retention interval.

We can determine if a chunk is may contain data past the retention interval by checking the min/max stats for the time column.


# Implementation Sketch

For chunks that may straddle retention bounds, the querier will attach a  `DeletePredicate` like:

```rust
DeletePredicate {
  range: TimestampRange {
         start: now() - retention_period,
         end: now()
  },
  exprs: None,
}
```

I would likely make a wrapper of a QuerierChunk that has the retention interval / new delete pedicate and wrap any chunks provided by the querier here: https://github.com/influxdata/influxdb_iox/blob/main/querier/src/namespace/query_access.rs#L81

I would also need to record and remember the retenion interval from the catatlog on `QuerierNamespace`


The benefit of this design is that it follows the established pattern of delete predicates and so can resused most of the code and test infrastructure

# Alternatives considered:
None really


cc @crepererum  and @NGA-TRAN

**Comment by NGA-TRAN** [comment]
Using `DelerePredicate` sounds good to me. And the Namespace now has a `retention_period_ns` field which should be a part of the `QuerierNamespace` as you suggested.

**Comment by crepererum** [comment]
From a current technical PoV this makes sense, however I was hoping to get rid of the chunk-bound delete predicates altogether since I may have convinced someone that this is actually a batch job :wink: 

IIRC the query optimization will suffer HEAVILY from this as well, since chunks with delete predicates are NOT grouped at the moment (i.e. you'll get 1 `ParquetExec` per file). So w/o adding grouping or any other optimization to the query path, I don't think we should do this and rather insert an extra `FilterExec` node above the whole `UnionExec` group that we produce.

**Comment by NGA-TRAN** [comment]
One more thing we may want to consider is we can/want to delete this data before deduplication. Chunk-level filter will enable that

**Comment by crepererum** [comment]
One thing we could do (and that would help delete predicates if we ever wanna bring them back to live) is to improve the plan expansion: instead of always isolating chunks with delete predicates (IIRC this is the current impl.) we could group them by predicates, i.e. if chunks share the same set of predicates, they could be grouped into the same `ParquetExec`/`RecordBatchesExec` node (reminder: delete predicates CAN ALWAYS run before de-dup!).

Thinking about it, we should probably do both: @alamb idea with pruning chunks early and only attaching the delete predicates to chunks "at the edge" and my idea that would improve delete predicate handling in general.

**Comment by alamb** [comment]
> Delete predicates (including this retention policy) can ALWAYS be pushed through de-dup because they solely act on tags and timestamp.

I don't understand this given https://github.com/influxdata/influxdb_iox/issues/6066 🤔

**Comment by crepererum** [comment]
> 

IIRC delete predicates can only act on tags and timestamps, not on fields. Or in other words: deletes are a primary-key-based set operation. And so are updates.

**Comment by alamb** [comment]
@crepererum  and I had a chat and the plan as I recall it is (please correct me if I am wrong):

Change the querier to 
1. skip any chunks (parquet files) that are entirely outside of the retention window
2. Add delete predicates to any parquet files that straddle the retention window and let the existing delete machinery handle the plans

While there are ideas to make the scan plan creation in iox_query better in various ways, we don't think this project justifies the effort yet.

**Comment by alamb** [comment]
I believe @NGA-TRAN may be planning to work on this as I am a bit behind and haven't started yet

**Comment by NGA-TRAN** [comment]
I will work on this after I finish must-have retention tasks which will be soon

**Comment by NGA-TRAN** [comment]
I start working on this today

**Comment by NGA-TRAN** [comment]
I think I will do this in 3 PRs (maybe more)
1. Make sure we have retention in namespace cache
2. Skipped chunks completely outside retention period
3. Add delete predicate (predicate if time outside retention period) into the remaining chunks
