### ISSUE TITLE
feat: Schema enforcement across chunks within the mutable buffer

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#636]
__Use case:__
IOx is envisioned to have a schema-on-write mode (with the possibility of adding more strict validations later). However, we also want to allow the schema to evolve over time and so the current thinking is to require the schema *within* a partition to have a consistent schema (consistent meaning when you union all the columns for a table together the names/types are the same). 

__Proposal:__
The goal is to allow IOx to reject data on write if it does not have a consistent schema with data that has already been written into that partition, 

__Current behaviour:_-

Right now, when data is inserted into the open active chunk, the mutable buffer ensures the schema of new rows is consistent with what is already in the currently active chunk (it has to given how it is structured).

However, there is no cross-chunk validation that new data incoming data has a consistent schema with the other chunks. Both chunks that are still present in the mutable buffer and chunks that may have been migrated to the read buffer and/or parquet files. 

__Desired behaviour:__
1. If a write comes into the immutable buffer that is inconsistent with data that is already in the immutable buffer (or was previously in the mutable buffer) the write should be rejected with an error message explaining what is inconsistent. 
2. The immutable buffer should be able to provide a description of the currently allowed schema in a format that can be sent to the routing tier so writes can be rejected higher up in the stack as well
3. The data structure for the schema and the logic of what makes data consistent should be defined in the `data_types` crate. 

__Alternatives considered:__
Describe other solutions or features you considered.

**Comment by pauldix** [comment]
This all looks right, just rephrasing to make sure we're all on the same page. There are two problems that people want to solve with schema validation:
1. Ensure that data types are consistent (i.e. a float column only accepts floats, int column ints, etc.)
2. Set schema and reject any writes attempting to add to, update, or change it (something like locking the schema)

Ideally, both of these things can happen at the front door when a write request comes in so that invalid writes can be rejected with  a proper error response returned to the client. However, because IOx can be configured an any number of ways with buffering, replications and subscriptions, this can't be guaranteed anywhere.

What this means is that we have to do schema validation in a few places. At a minimum, we need to do it in the MutableBuffer on whatever open chunks are being written to (writes could go to two partitions, which would hit two different chunks). We also need to do it when we persist a chunk to object storage. I think those two places are non-negotiable and have to be done no matter what. The open chunk spot because you can't actually write into the data structure that holds it without the validation. The chunk into object store spot so we can ensure that a partition's schema is consistent (note that a later chunk can have tables and columns that previous chunks don't have and this would still be a consistent schema).

On boot the server will read metadata about what partitions and chunks exist from object storage. I think this metadata should have schema at the partition level and the database level. The database level schema can be loaded into memory and can be used for validation in other places where we might want it. This could be when the write is initially accepted and converted into a ReplicatedWrite, or instead at the WAL Buffer, or in the MutableBuffer.

Whenever a chunk is persisted to object storage (whether in a new partition or not), the partition metadata should be updated (even without schema changes, it includes summary statistics). The database metadata should also be updated. We might just have the partition and database metadata all in a single file for efficiency and to ensure that the metadata updates are atomic.

If the server is configured to load data from a WAL, it will do so on boot based on the metadata from persisted chunks. The WAL will be loaded into the MutableBuffer and its schema re-validated as it goes.

Issues of changing schema over time are, in my mind, a separate thing. Well, we should be able to add a new table or column at any point, but that shouldn't fail validation unless the user has explicitly locked the schema. We'll have to deal with drops later (probably not that big of a deal) and type changes even later.

**Comment by alamb** [comment]
Make ssense @pauldix 

> On boot the server will read metadata about what partitions and chunks exist from object storage. I think this metadata should have schema at the partition level and the database level.

This makes a lot of sense

>  We also need to do it when we persist a chunk to object storage

If we pulled the schema from a partition on objectstore when the server started up, I think validating on write into the mutable buffer might be sufficient as there is now way data with an inconsistent schema can get into the system (as all data in any chunk being written to the object store already  its schema validated on entry to the mutable buffer).

**Comment by stuartcarnie** [comment]
@pauldix where do you expect the single source of true is for the database schema?
