### ISSUE TITLE
Write Info Service in RPC write mode

### ISSUE THREAD

**Issue by carols10cents** [influxdata/influxdb_iox#6444]
## Problem

In https://github.com/influxdata/influxdb_iox/issues/6421, I wanted to write a test that encoded any fix that I found.

Reproducing that bug involves knowing when written data has been persisted by the ingester.

Tests for the previous design used [the `WriteInfoService` to be able to see `ShardStatus`](https://github.com/influxdata/influxdb_iox/blob/d0d59064762514c0ec32020858ece7dcc15714c3/generated_types/protos/influxdata/iox/ingester/v1/write_info.proto).

There is also [this related issue for a public/end user API for a write's status](https://github.com/influxdata/influxdb_iox/issues/4354); I don't know if any further information has emerged since that was filed.

## Investigation so far

Because the router http write API is still the same and is still [returning a WriteSummary](https://github.com/influxdata/influxdb_iox/blob/d0d59064762514c0ec32020858ece7dcc15714c3/router/src/server/http.rs#L378) and [setting a write token header](https://github.com/influxdata/influxdb_iox/blob/d0d59064762514c0ec32020858ece7dcc15714c3/router/src/server/http.rs#L372), I naïvely thought the WriteInfoServiceServer just needed to be hooked up to the ingester and back through. 

However, what I've discovered is that the [WriteSummary is highly entwined with the concept of Shards and Sequences](https://github.com/influxdata/influxdb_iox/blob/d0d59064762514c0ec32020858ece7dcc15714c3/write_summary/src/lib.rs), and [when you give it unsequenced DmlMeta](https://github.com/influxdata/influxdb_iox/blob/d0d59064762514c0ec32020858ece7dcc15714c3/router/src/dml_handlers/rpc_write.rs#L112), it returns a whole lotta `None`.

So I'm starting to experiment with:

- changing the router from returning what it *sent* to the ingester to what it *received* from the ingester
- changing the ingester to return the sequence number it assigned the write from the timestamp oracle
- turning that sequence number plus the ingester UUID into a write token that could be used to check the status?

I have the current state of my experiments [on this branch](https://github.com/influxdata/influxdb_iox/pull/new/cn/write-info-service).

Is this a fool's errand? Does asking "is this data persisted" even make sense in this design? Is anything really knowable???

**Comment by domodwyer** [comment]
(summarising comments I left in Slack)

This used to be used for two things

* Show when a write had become readable in the ingester, without actually reading the data
* Wait for data to be persisted by the ingester

This interface was never used outside of tests, and probably shouldn't be brought back for the ingester2 model. It's better to observe the effects of the running system, rather than relying on a code path that was only exercised for tests. It seems rather round about / less concrete to ask the thing you are testing if it thinks something was persisted, rather than actually looking if something was persisted!

As writes now have no TTBR lag, there's no need for (1) because it happens synchronously with the RPC write. If the request completed, it should be readable.

It is trivial to observe if (2) has occurred by polling the catalog, or object storage itself without introducing an explicit API - this is both more robust, and what many other tests do.

**Comment by carols10cents** [comment]
Ok! I'm closing this then :)
