### ISSUE TITLE
Panics are not fatal

### ISSUE THREAD

**Issue by domodwyer** [influxdata/influxdb_iox#6777]
We recently observed an ingester who's workers had all died, but the panics had not propagated to the IOx process - it remained running in a zombie state, unable to make progress. The process not restarted because it didn't die.

Panics should be fatal by default, and caught where sensible/necessary to do so (perhaps when running datafusion plans where a panic for a single query might needlessly affect the availability of a querier as a whole, for example.)

**Comment by tustvold** [comment]
So panics not being fatal is somewhat intentional, or at the very least a known behaviour. This is discussed in more depth in https://github.com/influxdata/influxdb_iox/issues/1694 but basically boils down to it **being better to continue in a potentially degraded state, than to hard crash on any unexpected situation**. This does put the responsibility on some external system, be it k8s or an operator to intervene should some signal indicate the system is not healthy, but avoids hard crashing because of an unexpected situation that would otherwise have been non-fatal. For example, a number of chrono methods panic if timestamps are too large (although this is in the process of being fixed).

In the case of the workers, we may want to do something similar to what we did in OG - https://github.com/influxdata/influxdb_iox/pull/2234

I think it would also be fine if the ingester team has differing priorities, trade-offs and would prefer a more aggressive approach, this is just the approach that has been taken so far and has mostly worked fine.

**Comment by alamb** [comment]
I agree that making panics from DataFusion abort the querier process would reduce the querier availability significantly (as in I would expect to see restarts rather than the current behavior of "internal error")

I suspect there are different implicit assumptions about what `panic` (or `unwrap` or `expect`) do in different parts of the code
1.  `Querier`: If something panic's in datafusion (or arrow) which are largely read only, no data gets corrupted and there is a clear path to known good state. 
2. `Ingester`: I am pretty sure there are places in the ingester where `panic`s are used to signal "should not go on, manual intervention is required"

I am not quite sure what "by default" means in the description of this ticket, but it makes lots of sense to me to stop the ingester process if some invariant required for correctness is violated. 

Perhaps the ingester could be run in "abort on panic" mode but leave the querier running as is. Or perhaps in places critical to the ingester operation (that are unrecoverable) `process::abort` could be called explicitly.

**Comment by alamb** [comment]
> being better to continue in a potentially degraded state, than to hard crash on any unexpected situation.

I think this depends on which component is running and what invariant has been violated -- it makes sense for the querier to go on after a panic but maybe not the ingester

**Comment by tustvold** [comment]
> I think this depends on which component is running and what invariant has been violated

:100: the key thing is the "**any**", treating anything unexpected regardless of context as fatal, is likely overly pessimistic. Sure if a failure would correspond to data loss, crashing noisily is probably best, but provided the state of the system is still well defined...

**Comment by domodwyer** [comment]
> better to continue in a potentially degraded state, than to hard crash on any unexpected situation

I think this is just two sides of the same coin - I'd rather have my service explode when something terrible and unexpected happens, and if I discover chrono is trying to parse large timestamps (but expect the system to make progress regardless) wrap it in a catch and handle it appropriately rather than pretending all panics are OK. Making that an explicit choice of behaviour for a service choice sounds like a reasonable step forward :+1: , though I still think panic-is-fatal is a good default.

> and there is a clear path to known good state.

> the state of the system is still well defined

That's trickier a statement than it first seams - it's quite possible to wind up in a terrible state because you took a mutex and panicked half way through before releasing it, breaking some internal invariant. It's fundamentally tricky to reason about this stuff in our code, let alone in 3rd party code that might rely on panics tearing down shared state, which instead will be retained and used.

> I am not quite sure what "by default" means 

Today, we have no choice - the default and only behaviour is to catch panics and continue running. I propose making this a choice.

**Comment by alamb** [comment]
> That's trickier a statement than it first seams - it's quite possible to wind up in a terrible state because you took a mutex and panicked half way through before releasing it,

This is true in theory, but thankfully we haven't seen anything like this in the querier over the last 2 years that I am aware of

As long as the querier process will not get aborted if there is an `unwrap` / `expect` / `panic` in datafusion code or one of our dependencies I am all for this proposal

**Comment by domodwyer** [comment]
> This is true in theory, but thankfully we haven't seen anything like this in the querier over the last 2 years that I am aware of

That you know of ;) 

I will PR this shortly and @ the world :+1:
