### ISSUE TITLE
InfluxQL-IOx: Rewrite fully anchored regular expressions

### ISSUE THREAD

**Issue by stuartcarnie** [influxdata/influxdb_iox#6902]
Teach the InfluxQL planner how to rewrite fully-anchored regular expressions to `=` and `!=` expressions.

# Background

Regular expressions which begin with the start anchor (`^`) and end with the end anchor (`$`) are rewritten by the InfluxQL query engine, to their equivalent equality operator. For example, using the regex match operator (`=~`), the following predicate

```sql
WHERE tag0 =~ /^val00$/ 
```

is rewritten to

```sql
WHERE tag0 = 'val00'
```

Similarly, using the regex not match operator (`!~`):

```sql
WHERE tag0 !~ /^val00$/ 
```

is transformed to

```sql
WHERE tag0 != 'val00'
```

# Requirements

Implement a new DataFusion logical expression rewriter that examines a DataFusion expression tree and rewrites the regular expressions using the aforementioned rules. It makes most sense to add the rewriter to the `rewrite_conditional_expr` function:

https://github.com/influxdata/influxdb_iox/blob/47b47f225be70b54adc1b846f3b280fbe533760e/iox_query/src/plan/influxql/planner.rs#L509-L511

If it makes sense, the `FixRegularExpressions` rewriter could be updated to implement the required behaviour:

https://github.com/influxdata/influxdb_iox/blob/47b47f225be70b54adc1b846f3b280fbe533760e/iox_query/src/plan/influxql/planner.rs#L523-L527

> **Note**
>
> This rewriting should happen before tag key existence checking as described in #6901, to ensure empty regular expression literals are treated as existence expressions.

**Comment by crepererum** [comment]
Note that we already have two rewrite steps for regex expressions which we also use for SQL:

1. Transform IOx-specific regex to DF-regex: https://github.com/influxdata/influxdb_iox/blob/1d2003d3852779f0dcb1e8eab9791fa28baa37e6/iox_query/src/logical_optimizer/influx_regex_to_datafusion_regex.rs#L11-L18
2. Simplify regex expressions: https://github.com/apache/arrow-datafusion/blob/9798fbcab1e04123f05e7692475e104310e0473a/datafusion/optimizer/src/simplify_expressions/regex.rs#L22-L29

The 2nd step currently only rewrites regex to `IS IN`-like constructs and ignores anchoring altogether. However we could extend this upstream.

**Comment by wolffcm** [comment]
As I understand it:
- We need to rewrite expressions of the form `tag0 != ''` to `tag0 is null` (#6901). This is not a valid transformation if we're dealing with SQL; I don't see how we can upstream this rewrite as it's quite InfluxQL specific. Call this `TagKeyExistenceRewrite`
- We also need to treat fully anchored regex comparisons in a similar way, so that `tag0 = /^$/` ends up getting treated the same as `tag0 = ''`, which would ultimately be rewritten as `tag0 is null`, which is this issue. We could upstream this as an addition to `SimplifyExpressions` as @crepererum notes.

Would it be possible when logically optimizing an InfluxQL query to run `SimplifyExpressions` (part of the standard passes that we get from upstream) before we run `TagKeyExistenceRewrite`? At the moment most of the rewrites seem to occur before we hand off the logical plan to the logical optimizer.





Since we need this rewrite to get the correct behavior for the existence check in #6901, it seems like we

**Comment by crepererum** [comment]
Sure you can run `SimplifyExpressions` multiple time if you want. IIRC the upstream passes are exported as public interfaces, so you can just instantiate and run them on any (sub)plan.

**Comment by wolffcm** [comment]
I opened https://github.com/apache/arrow-datafusion/pull/6369 upstream for this

**Comment by wolffcm** [comment]
DataFusion will rewrite fully anchored regexes as part of `SimplifyExpressions` now.

We may or may not need to invoke this pass early (in the InfluxQL planner before handing off to DF logical optimizer) depending on how https://github.com/influxdata/influxdb_iox/issues/6901 works out.
