### ISSUE TITLE
Catalog should use NamespaceName when creating namespaces

### ISSUE THREAD

**Issue by domodwyer** [influxdata/influxdb_iox#7592]
The catalog `NamespaceRepo::create()` accepts a bare `&str`:

https://github.com/influxdata/influxdb_iox/blob/d7dc3059728f8dc129eb8266fa5be39fe81a0b79/iox_catalog/src/interface.rs#L333-L339

This allows namespaces of arbitrary names to be created, bypassing namespace name validation.

Instead this call should take `name: &NamespaceName`. The type system upholds the invariant that any `NamespaceName` instance contains a valid namespace name. By accepting this instead of `&str`, the catalog can transitively uphold the same invariant - all namespaces created through the `NamespaceRepo::create()` use valid names.

**Comment by wiedld** [comment]
Note: I start on this approach, but the diff grew rather large -- especially since we use all over the tests.

Thought of another approach. Use a generic create() with the type declares in the trait method, but then specific implementations (for the memory paradigms used in tests) can have a separate implemention which still accepts the &str --> and wraps around the trait method.

I started down this path a bit (still debugging), but it looks something like this https://github.com/influxdata/influxdb_iox/commit/96cbc534ea71d48635036ad87777a5e01765b907.
