### ISSUE TITLE
chore: switch to stable rust

### ISSUE THREAD

**Issue by mkmik** [influxdata/influxdb_iox#809]
Ideally we should target stable rust. Currently this is what is preventing us form building on stable rust:

- [ ] arrow rust upstream uses deprecated `packed_simd_2` (which requires nightly). We can either wait or contribute upstream to switch stdsimd which is not deprecated.

**Comment by carols10cents** [comment]
History: https://github.com/influxdata/influxdb_iox/issues/115, I'll close that one in favor of this one :)

**Comment by carols10cents** [comment]
Looking into this a tiny bit:

- By "stdsimd", I assume you mean the work being done in https://github.com/rust-lang/stdsimd
- The crate in that repo is named [`core_simd`](https://github.com/rust-lang/stdsimd/blob/0682c31fcee752a5530b4f45ba0e726a85654bcd/crates/core_simd/Cargo.toml#L2) and does not appear to be published on crates.io yet
- I don't know how arrow feels about git dependencies; I'm guessing they wouldn't be interested because that would prevent the arrow crates from being published on crates.io
- So I believe this to be blocked on `core_simd` being published.

Please correct me if I'm wrong!
