### ISSUE TITLE
chore: test or rework object_store wrapper

### ISSUE THREAD

**Issue by mkmik** [influxdata/influxdb_iox#863]
(pardon my sloppy writing; I'm on mobile but want to jolt this down before forgetting it).

PR #854 showed that we don't test the objectstore wrapper, like:

https://github.com/influxdata/influxdb_iox/blob/9e521a2ea125c6b5c2822c261970bb2f1bc9a094/object_store/src/lib.rs#L280

We should either test it or perhaps consider not using such a wrapper in the first place (aren't trait objects, or whatever Box dyn things are called, a lower maintenance alternative?)

**Comment by carols10cents** [comment]
First, we should definitely be testing the wrapper code 😳😰

Next, there are a few issues with using trait objects.

If we switch to the `Server` struct having a trait object like:

```
pub struct Server<M: ConnectionManager> {
    pub store: Arc<dyn ObjectStoreApi>,
    // ...
}
```

then the associated `Path` and `Error` types have to become trait objects too, and we lose the compile-time checking that each object store type is using the appropriate object store path type. That check would need to be moved to runtime, and we do have a bit of runtime checking happening in the delegation code, but the associated types ensure at compile time that as long as we always construct a path through the `ObjectStoreApi` `new_path` function, it'll be the correct type. Which would be true with the trait object as well because the implementation of `new_path` for each object store would always return a particular `Path` type, it just... feels more coincidental and less "encoded in the type system" to me than associated types? Perhaps that's just a personal mental problem.

Then, traits used with trait objects have to be object-safe, and one restriction on that is they can't use generics, so `put` would need to use a boxed stream rather than a generic stream of bytes.

I agree this code isn't ideal, but I'm not sure any other way would be better, particularly... but please feel free to change it if you'd like to make different tradeoffs!

**Comment by mkmik** [comment]
> First, we should definitely be testing the wrapper code 😳😰

Perhaps we could have the tests for each provider specific module use the main wrappers instead of calling the functions from super?

**Comment by mkmik** [comment]
> and we lose the compile-time checking that each object store type is using the appropriate object store path type.

it's not clear to me why we need a per-cloud provider filepath type. Couldn't we have a common Path type that contains `Vec<String>` and then have a per-cloud-provider transformer that turns that into implementation specific paths?

**Comment by carols10cents** [comment]
Google, S3, Azure, and in memory all use the same path logic, so the thinking was these should be shared. File paths use different logic.

**Comment by mkmik** [comment]
I see; but while they have different logic, their API should be the same, right?

If we "buffer" all operations on paths by recording the user intent before doing the translation logic, we can avoid having to know the concrete type until the objectstore implementation calls the conversion logic.

It's slightly less efficient but I wonder if path management is worth optimizing so much, especially if it costs so much boilerplate code.

**Comment by shepmaster** [comment]
@pauldix — AFAIK, you've had the most opportunity to make use of these APIs, maybe you'd be able to weigh in on how you've felt about them?

If the team thinks that reworking this code is a priority, we'd be happy to pivot to that!

**Comment by mkmik** [comment]
fwiw, I don't think this is a priority; we noticed a missing test in this layer and I was just asking a few questions, mostly with educational intent

**Comment by jacobmarble** [comment]
@carols10cents can this be closed?

**Comment by carols10cents** [comment]
I think so. If this becomes a priority, we can reopen.
