### ISSUE TITLE
refactor: unify serialization of database rules

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb_iox#973]
Since we're now using generated proto types for the serialization/deserialization of `DatabaseRules` in the API, I think we should remove the Serde derived serialization in `database_rules.rs`. However, right now that is used in the `server` crate to persist the rules in a file in object storage.

Can we unify the formats so that object storage is what's understood by the API and vice versa?

**Comment by alamb** [comment]
@pauldix  I think this the duplication (once via protobuf and once in data_types was intentional). It is a pain but it means that the client isn't using the same internal structure as the server. 

I think it would be a shame if we lost the ability to serialize the types using JSON (and I have a sneaky plan to use serde to turn things into arrow as well....)

**Comment by tustvold** [comment]
I'd be in support of this, and I actually intended to do this, as I didn't realise serde was being used outside the old HTTP API. There are things the use of serde complicates doing, e.g. further constraining the Rust types to only represent valid configurations, and it makes sense to me to only have one long-term backwards/forwards compatible representation of these types.

> It is a pain but it means that the client isn't using the same internal structure as the server.

The client still wouldn't be using the same internal structure as the server, if anything moving the persistence to use protobuf seems like a natural extension of the same philosophy?

**Comment by alamb** [comment]
I probably don't understand the proposal.
