### ISSUE TITLE
chore: upgrade to new version of flatbuffers

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb_iox#992]
Arrow Flight upgraded flatbuffers and so must we. However, the API changed a bit so we need to take a little more thought in how we do the upgrade. Mentioned in #989 by @tustvold.

**Comment by carols10cents** [comment]
So I don't think we *have* to upgrade, because IOx's flatbuffers should never be used in the same context as Arrow flatbuffers, correct? 

If we want to limit the number of crates in our dependency tree, sure, but for API compatibility, I don't think it's necessary.

That being said, I'm happy to work on this unless someone else really wants to! Just wanted to make sure I wasn't missing anything about the reasons.

**Comment by tustvold** [comment]
It is conceivable a client at some point may need to use both, particularly as the client and server are currently the same binary, but my major motivation was reducing the number of dependencies as you ascertained :+1:
